# Generated by Django 5.2.13 on 2026-04-27 11:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfpConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('afp_nombre', models.CharField(max_length=80)),
                ('vigencia_mes', models.CharField(help_text='Formato YYYY-MM', max_length=7)),
                ('aporte_obligatorio_pct', models.DecimalField(decimal_places=3, default=Decimal('10.000'), max_digits=6)),
                ('comision_flujo_pct', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('comision_mixta_pct', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('prima_seguro_pct', models.DecimalField(decimal_places=3, default=Decimal('1.370'), max_digits=6)),
                ('remuneracion_max_asegurable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], db_column='estado', default='activo', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
            ],
            options={
                'db_table': 'configuracion_afp',
                'ordering': ['-vigencia_mes', 'afp_nombre'],
                'indexes': [models.Index(fields=['afp_nombre'], name='configuraci_afp_nom_8564da_idx'), models.Index(fields=['vigencia_mes'], name='configuraci_vigenci_12071c_idx'), models.Index(fields=['status'], name='configuraci_estado_34bdb1_idx')],
                'constraints': [models.UniqueConstraint(fields=('afp_nombre', 'vigencia_mes'), name='uniq_config_afp_nombre_vigencia')],
            },
        ),
        migrations.CreateModel(
            name='CompensationConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('descuento', 'Descuento')], max_length=20)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porcentaje', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('monto_fijo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('aplica_base_imponible', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], db_column='estado', default='activo', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
            ],
            options={
                'db_table': 'configuracion_remuneracion',
                'ordering': ['tipo', 'orden', 'nombre'],
                'indexes': [models.Index(fields=['tipo'], name='configuraci_tipo_48de49_idx'), models.Index(fields=['codigo'], name='configuraci_codigo_2938f0_idx'), models.Index(fields=['status'], name='configuraci_estado_d391c8_idx'), models.Index(fields=['orden'], name='configuraci_orden_eb4d3b_idx')],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'codigo'), name='uniq_config_remuneracion_tipo_codigo')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPayroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo', models.CharField(help_text='Formato YYYY-MM', max_length=7)),
                ('modalidad', models.CharField(choices=[('plazo_indeterminado', 'Plazo Indeterminado'), ('plazo_determinado', 'Plazo Determinado'), ('subsidio', 'Subsidio'), ('locacion', 'Locación de Servicios'), ('consultoria', 'Consultoría')], max_length=30)),
                ('meta_presupuestal', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('procesando', 'En Proceso'), ('generada', 'Generada'), ('aprobada', 'Aprobada'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], db_column='estado', default='borrador', max_length=20)),
                ('total_trabajadores', models.PositiveIntegerField(default=0)),
                ('total_remuneracion_bruta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_neto_pagar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_essalud', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_aporte_afp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_onp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('fecha_generacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('usuario_aprobacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planillas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_generacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planillas_generadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planilla_mensual',
                'ordering': ['-periodo', 'modalidad'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(choices=[('mensual', 'Mensual'), ('quincenal', 'Quincenal'), ('semanal', 'Semanal'), ('extraordinario', 'Extraordinario')], max_length=20)),
                ('fecha_pago_programada', models.DateField()),
                ('fecha_pago_ejecutada', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], db_column='estado', default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios_pago', to='payroll.monthlypayroll')),
                ('usuario_programacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendarios_programados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendario_pago',
                'ordering': ['fecha_pago_programada'],
            },
        ),
        migrations.CreateModel(
            name='PayrollDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area_nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('sistema_pensiones', models.CharField(max_length=30)),
                ('tipo_comision_afp', models.CharField(blank=True, max_length=10, null=True)),
                ('cuspp', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_laboral', models.CharField(choices=[('activo', 'Activo'), ('licencia', 'De Licencia'), ('suspendido', 'Suspendido'), ('descanso_medico', 'Descanso Médico')], default='activo', help_text='Estado laboral del empleado en el periodo', max_length=20)),
                ('dias_laborados', models.PositiveIntegerField(default=30)),
                ('dias_no_laborados', models.PositiveIntegerField(default=0)),
                ('dias_subsidiados', models.PositiveIntegerField(default=0)),
                ('remuneracion_basica', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('asignacion_familiar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('bonificacion_especial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('otras_bonificaciones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_haberes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('aporte_afp_obligatorio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('comision_afp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('prima_seguro_afp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_afp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('aporte_onp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('renta_quinta_categoria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tiene_suspension_renta_cuarta', models.BooleanField(default=False, help_text='Indica si el empleado presentó suspensión de retención de renta de 4ta categoría')),
                ('tope_suspension_anual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto acumulado anual para control de tope de suspensión', max_digits=12)),
                ('descuentos_judiciales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('prestamos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('otros_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('essalud', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('datos_laborales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_planilla', to='contracts.employmentdata')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_planilla', to='employees.employee')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='payroll.monthlypayroll')),
            ],
            options={
                'db_table': 'detalle_planilla',
                'ordering': ['area_nombre', 'empleado__apellido_paterno'],
            },
        ),
        migrations.CreateModel(
            name='PayrollConcept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('descuento', 'Descuento')], max_length=20)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('configuracion_concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_planilla', to='payroll.compensationconfiguration')),
                ('detalle_planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='payroll.payrolldetail')),
            ],
            options={
                'db_table': 'concepto_planilla',
                'ordering': ['tipo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo_pdf', models.FileField(blank=True, help_text='Archivo PDF de la boleta', null=True, upload_to='boletas_pago/%Y/%m/')),
                ('status', models.CharField(choices=[('generada', 'Generada'), ('enviada', 'Enviada'), ('descargada', 'Descargada')], db_column='estado', default='generada', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio_email', models.DateTimeField(blank=True, null=True)),
                ('fecha_descarga', models.DateTimeField(blank=True, null=True)),
                ('hash_documento', models.CharField(blank=True, help_text='SHA-256 del PDF', max_length=64, null=True)),
                ('detalle_planilla', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleta', to='payroll.payrolldetail')),
            ],
            options={
                'db_table': 'boleta_pago',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='TaxParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anio', models.PositiveIntegerField(help_text='Año fiscal (YYYY)')),
                ('valor_uit', models.DecimalField(decimal_places=2, help_text='Valor de la UIT en soles para el año fiscal', max_digits=10)),
                ('tope_renta_cuarta_uit', models.DecimalField(decimal_places=2, default=Decimal('45.00'), help_text='Tope de exoneración en UITs (generalmente 45 UITs)', max_digits=5)),
                ('porcentaje_renta_cuarta', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Porcentaje de retención de renta de 4ta categoría', max_digits=5)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], db_column='estado', default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('created_by', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_uit_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'configuracion_uit',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='MassDeduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo', models.CharField(help_text='Formato YYYY-MM', max_length=7)),
                ('archivo_origen', models.FileField(help_text='Archivo Excel con descuentos masivos', upload_to='descuentos_masivos/%Y/%m/')),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('registros_procesados', models.PositiveIntegerField(default=0)),
                ('registros_error', models.PositiveIntegerField(default=0)),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('aplicado', 'Aplicado'), ('anulado', 'Anulado')], db_column='estado', default='pendiente', max_length=20)),
                ('errores_log', models.TextField(blank=True, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('configuracion_concepto', models.ForeignKey(limit_choices_to={'tipo': 'descuento'}, on_delete=django.db.models.deletion.PROTECT, related_name='descuentos_masivos', to='payroll.compensationconfiguration')),
                ('usuario_carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descuentos_masivos_cargados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'descuento_masivo',
                'ordering': ['-fecha_carga'],
                'indexes': [models.Index(fields=['periodo'], name='descuento_m_periodo_3f0496_idx'), models.Index(fields=['status'], name='descuento_m_estado_529e99_idx'), models.Index(fields=['-fecha_carga'], name='descuento_m_fecha_c_fd69ea_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='monthlypayroll',
            index=models.Index(fields=['periodo'], name='planilla_me_periodo_a636eb_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlypayroll',
            index=models.Index(fields=['modalidad'], name='planilla_me_modalid_8ab38a_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlypayroll',
            index=models.Index(fields=['status'], name='planilla_me_estado_90af76_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlypayroll',
            index=models.Index(fields=['meta_presupuestal'], name='planilla_me_meta_pr_7719eb_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlypayroll',
            index=models.Index(fields=['-created_at'], name='planilla_me_fecha_c_a4e5e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlypayroll',
            constraint=models.UniqueConstraint(fields=('periodo', 'modalidad', 'meta_presupuestal'), name='uniq_planilla_periodo_modalidad_meta'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['planilla'], name='calendario__planill_b97353_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['fecha_pago_programada'], name='calendario__fecha_p_f885ec_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['status'], name='calendario__estado_77e9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['-created_at'], name='calendario__fecha_c_9cde4c_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolldetail',
            index=models.Index(fields=['planilla'], name='detalle_pla_planill_a74c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolldetail',
            index=models.Index(fields=['empleado'], name='detalle_pla_emplead_ceabbe_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolldetail',
            index=models.Index(fields=['dni'], name='detalle_pla_dni_98b301_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolldetail',
            index=models.Index(fields=['sistema_pensiones'], name='detalle_pla_sistema_89a8b1_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolldetail',
            index=models.Index(fields=['banco'], name='detalle_pla_banco_9fcabd_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrolldetail',
            constraint=models.UniqueConstraint(fields=('planilla', 'empleado'), name='uniq_detalle_planilla_empleado'),
        ),
        migrations.AddIndex(
            model_name='payrollconcept',
            index=models.Index(fields=['detalle_planilla'], name='concepto_pl_detalle_1ac869_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollconcept',
            index=models.Index(fields=['tipo'], name='concepto_pl_tipo_045406_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollconcept',
            index=models.Index(fields=['codigo'], name='concepto_pl_codigo_c3c02f_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['detalle_planilla'], name='boleta_pago_detalle_79aeea_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['status'], name='boleta_pago_estado_86c3ac_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['-fecha_generacion'], name='boleta_pago_fecha_g_c43e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='taxparameter',
            index=models.Index(fields=['anio'], name='configuraci_anio_b21674_idx'),
        ),
        migrations.AddIndex(
            model_name='taxparameter',
            index=models.Index(fields=['status'], name='configuraci_estado_036f7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxparameter',
            constraint=models.UniqueConstraint(fields=('anio',), name='uniq_configuracion_uit_anio'),
        ),
    ]
