# Generated by Django 5.2.13 on 2026-05-09 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_tenant_contractamendment_tenant_and_more'),
        ('employees', '0002_alter_academicrecord_unique_together_and_more'),
        ('payroll', '0001_initial'),
        ('tenancy', '0004_supportsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='afpconfiguration',
            name='uniq_config_afp_nombre_vigencia',
        ),
        migrations.RemoveConstraint(
            model_name='compensationconfiguration',
            name='uniq_config_remuneracion_tipo_codigo',
        ),
        migrations.RemoveConstraint(
            model_name='monthlypayroll',
            name='uniq_planilla_periodo_modalidad_meta',
        ),
        migrations.RemoveConstraint(
            model_name='payrolldetail',
            name='uniq_detalle_planilla_empleado',
        ),
        migrations.RemoveConstraint(
            model_name='taxparameter',
            name='uniq_configuracion_uit_anio',
        ),
        migrations.AddField(
            model_name='afpconfiguration',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='compensationconfiguration',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='massdeduction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='monthlypayroll',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='payrollconcept',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='taxparameter',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddConstraint(
            model_name='afpconfiguration',
            constraint=models.UniqueConstraint(fields=('tenant', 'afp_nombre', 'vigencia_mes'), name='uniq_config_afp_nombre_vigencia_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='compensationconfiguration',
            constraint=models.UniqueConstraint(fields=('tenant', 'tipo', 'codigo'), name='uniq_config_remuneracion_tipo_codigo_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='monthlypayroll',
            constraint=models.UniqueConstraint(fields=('tenant', 'periodo', 'modalidad', 'meta_presupuestal'), name='uniq_planilla_periodo_modalidad_meta_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='payrolldetail',
            constraint=models.UniqueConstraint(fields=('tenant', 'planilla', 'empleado'), name='uniq_detalle_planilla_empleado_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='taxparameter',
            constraint=models.UniqueConstraint(fields=('tenant', 'anio'), name='uniq_configuracion_uit_anio_per_tenant'),
        ),
    ]
