# Generated by Django 5.2.13 on 2026-05-28 00:27
# (manually rewritten: use DeleteModel directly; all inter-model FKs are
#  within this app so no cross-app dependency; SQLite DROP TABLE handles indexes.)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_remove_afpconfiguration_uniq_config_afp_nombre_vigencia_and_more'),
    ]

    operations = [
        # Delete leaf models first (those with FKs pointing to other payroll models)
        migrations.DeleteModel(
            name='PaySlip',
        ),
        migrations.DeleteModel(
            name='PayrollConcept',
        ),
        migrations.DeleteModel(
            name='PaymentSchedule',
        ),
        migrations.DeleteModel(
            name='PayrollDetail',
        ),
        # Now delete parent models
        migrations.DeleteModel(
            name='MonthlyPayroll',
        ),
        migrations.DeleteModel(
            name='MassDeduction',
        ),
        migrations.DeleteModel(
            name='CompensationConfiguration',
        ),
        migrations.DeleteModel(
            name='AfpConfiguration',
        ),
        migrations.DeleteModel(
            name='TaxParameter',
        ),
    ]
