# Generated by Django 5.2.13 on 2026-05-28 01:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0003_drop_legacy_payroll'),
        ('tenancy', '0004_supportsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimenConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regimen_code', models.CharField(db_index=True, max_length=24)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('vacation_days_annual', models.IntegerField()),
                ('applies_asignacion_familiar', models.BooleanField(default=True)),
                ('applies_cts', models.BooleanField(default=True)),
                ('applies_gratification', models.BooleanField(default=True)),
                ('cts_deposit_months', models.JSONField(default=list)),
                ('gratification_months', models.JSONField(default=list)),
                ('severance_indemnization_formula', models.CharField(max_length=64)),
                ('essalud_rate_override', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('policy_notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'payroll_regimen_config',
                'ordering': ['regimen_code', '-valid_from'],
                'constraints': [models.UniqueConstraint(fields=('regimen_code', 'valid_from'), name='uniq_regimen_code_validfrom')],
            },
        ),
        migrations.CreateModel(
            name='TaxParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('PEN', 'Soles'), ('RATE', 'Tasa'), ('UIT', 'Múltiplo UIT')], max_length=8)),
                ('source_law', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'payroll_tax_parameter',
                'ordering': ['code', '-valid_from'],
                'constraints': [models.UniqueConstraint(fields=('code', 'valid_from'), name='uniq_taxparam_code_validfrom')],
            },
        ),
        migrations.CreateModel(
            name='PayrollConcept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('sunat_code', models.CharField(blank=True, default='', max_length=4)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('INCOME', 'Ingreso'), ('DEDUCTION', 'Descuento'), ('CONTRIBUTION_EMPLOYER', 'Aporte empleador'), ('TAX', 'Tributo')], max_length=24)),
                ('subcategory', models.CharField(blank=True, default='', max_length=24)),
                ('affects_income_tax', models.BooleanField(default=False)),
                ('affects_afp_onp', models.BooleanField(default=False)),
                ('affects_essalud', models.BooleanField(default=False)),
                ('affects_cts', models.BooleanField(default=False)),
                ('affects_gratification', models.BooleanField(default=False)),
                ('is_remunerative', models.BooleanField(default=True)),
                ('is_variable', models.BooleanField(default=False)),
                ('cts_min_frequency', models.IntegerField(default=3)),
                ('formula_code', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_children', to='payroll.payrollconcept')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'payroll_concept',
                'ordering': ['sunat_code', 'code'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_concept_tenant_code')],
            },
        ),
    ]
