# Generated by Django 5.2.13 on 2026-05-28 03:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_b14_termination_severance'),
        ('employees', '0011_b12_legajo_content'),
        ('payroll', '0004_catalog_models'),
        ('tenancy', '0004_supportsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('has_family_allowance', models.BooleanField(default=False)),
                ('regimen_laboral', models.CharField(max_length=20)),
                ('pension_regime', models.CharField(choices=[('ONP', 'ONP'), ('AFP_INTEGRA', 'AFP Integra'), ('AFP_PRIMA', 'AFP Prima'), ('AFP_PROFUTURO', 'AFP Profuturo'), ('AFP_HABITAT', 'AFP Hábitat')], max_length=20)),
                ('afp_commission_type', models.CharField(blank=True, choices=[('FLUJO', 'Flujo'), ('MIXTA', 'Mixta'), ('SALDO', 'Saldo')], default='', max_length=8)),
                ('cuspp', models.CharField(blank=True, default='', max_length=12)),
                ('health_regime', models.CharField(choices=[('ESSALUD', 'EsSalud'), ('EPS', 'EPS')], max_length=16)),
                ('eps_provider', models.CharField(blank=True, default='', max_length=64)),
                ('cci', models.CharField(blank=True, default='', max_length=20)),
                ('bank_code', models.CharField(blank=True, default='', max_length=8)),
                ('bank_account', models.CharField(blank=True, default='', max_length=20)),
                ('permission_level', models.IntegerField(default=6)),
                ('source', models.CharField(choices=[('MIGRATION', 'Migración inicial desde EmploymentData/Contract'), ('MANUAL', 'Creado manualmente por RRHH'), ('CONTRACT_AMENDMENT', 'Generado por adenda de contrato')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensations', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'payroll_compensation',
                'ordering': ['-valid_from'],
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'employee', '-valid_from'], name='payroll_com_tenant__a543e2_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'valid_from'), name='uniq_compensation_employee_validfrom')],
            },
        ),
    ]
