# Generated by Django 5.2.13 on 2026-04-26 17:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('employees', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionVacaciones',
            fields=[
                ('configuracion_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_configuracion', models.CharField(choices=[('general', 'General'), ('area', 'Por Área'), ('empleado', 'Por Empleado'), ('cargo', 'Por Cargo')], max_length=15)),
                ('dias_por_ano', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('dias_adicionales_antiguedad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('anos_para_adicional', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('permite_acumulacion', models.BooleanField(default=True)),
                ('max_dias_acumulables', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)])),
                ('dias_minimos_solicitud', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('dias_maximos_solicitud', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('dias_anticipacion_minima', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)])),
                ('tipo_calculo', models.CharField(choices=[('dias_calendario', 'Días Calendario'), ('dias_habiles', 'Días Hábiles'), ('proporcional', 'Proporcional')], default='dias_calendario', max_length=20)),
                ('incluye_feriados', models.BooleanField(default=True)),
                ('incluye_fines_semana', models.BooleanField(default=True)),
                ('requiere_aprobacion_jefe', models.BooleanField(default=True)),
                ('requiere_aprobacion_rrhh', models.BooleanField(default=True)),
                ('niveles_aprobacion', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('permite_fraccionamiento', models.BooleanField(default=True)),
                ('min_dias_por_fraccion', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('max_fracciones_por_ano', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio_vigencia', models.DateField()),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_vacaciones', to='organization.area')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_vacaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_vacaciones', to='employees.empleado')),
            ],
            options={
                'db_table': 'configuracion_vacaciones',
            },
        ),
        migrations.CreateModel(
            name='PeriodoVacacional',
            fields=[
                ('periodo_id', models.AutoField(primary_key=True, serialize=False)),
                ('ano_periodo', models.IntegerField()),
                ('fecha_inicio_periodo', models.DateField()),
                ('fecha_fin_periodo', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('dias_correspondientes', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('365.0'))])),
                ('dias_adicionales', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('30.0'))])),
                ('dias_totales', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('365.0'))])),
                ('dias_gozados', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('dias_pendientes', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('dias_vencidos', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('estado_periodo', models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='activo', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos', to='time_off.configuracionvacaciones')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periodos_vacacionales', to='contracts.contratosadendas')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_vacacionales_creados', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_vacacionales', to='employees.empleado')),
            ],
            options={
                'db_table': 'periodos_vacacionales',
            },
        ),
        migrations.CreateModel(
            name='SolicitudVacaciones',
            fields=[
                ('solicitud_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_solicitud', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('adelanto_vacaciones', 'Adelanto de Vacaciones'), ('fraccionamiento', 'Fraccionamiento'), ('postergacion', 'Postergación')], default='vacaciones', max_length=25)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_solicitados', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('365.0'))])),
                ('medio_dia', models.BooleanField(default=False)),
                ('motivo_solicitud', models.TextField()),
                ('observaciones_empleado', models.TextField(blank=True, null=True)),
                ('estado_solicitud', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('en_revision', 'En Revisión'), ('aprobada_jefe', 'Aprobada por Jefe'), ('aprobada_rrhh', 'Aprobada por RRHH'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('en_goce', 'En Goce'), ('finalizada', 'Finalizada')], default='borrador', max_length=20)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por_jefe', models.BooleanField(default=False)),
                ('fecha_aprobacion_jefe', models.DateTimeField(blank=True, null=True)),
                ('observaciones_jefe', models.TextField(blank=True, null=True)),
                ('aprobado_por_rrhh', models.BooleanField(default=False)),
                ('fecha_aprobacion_rrhh', models.DateTimeField(blank=True, null=True)),
                ('observaciones_rrhh', models.TextField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('fecha_rechazo', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_canceladas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_vacaciones', to='employees.empleado')),
                ('jefe_aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas_como_jefe', to='employees.empleado')),
                ('periodo_vacacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='time_off.periodovacacional')),
                ('rechazado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_rechazadas', to=settings.AUTH_USER_MODEL)),
                ('rrhh_aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas_rrhh', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitudes_vacaciones',
            },
        ),
        migrations.CreateModel(
            name='HistorialSolicitudVacaciones',
            fields=[
                ('historial_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_accion', models.CharField(choices=[('creacion', 'Creación'), ('envio', 'Envío'), ('aprobacion_jefe', 'Aprobación Jefe'), ('aprobacion_rrhh', 'Aprobación RRHH'), ('rechazo', 'Rechazo'), ('cancelacion', 'Cancelación'), ('modificacion', 'Modificación'), ('inicio_goce', 'Inicio de Goce'), ('fin_goce', 'Fin de Goce'), ('interrupcion', 'Interrupción'), ('reincorporacion', 'Reincorporación')], max_length=20)),
                ('descripcion_accion', models.TextField()),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('datos_adicionales', models.JSONField(blank=True, null=True)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario_accion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_vacaciones', to=settings.AUTH_USER_MODEL)),
                ('solicitud_vacaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='time_off.solicitudvacaciones')),
            ],
            options={
                'db_table': 'historial_solicitudes_vacaciones',
            },
        ),
        migrations.CreateModel(
            name='GoceVacaciones',
            fields=[
                ('goce_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio_real', models.DateField()),
                ('fecha_fin_real', models.DateField()),
                ('fecha_reincorporacion', models.DateField(blank=True, null=True)),
                ('dias_gozados', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('365.0'))])),
                ('estado_goce', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('interrumpido', 'Interrumpido'), ('cancelado', 'Cancelado')], default='programado', max_length=15)),
                ('fecha_interrupcion', models.DateField(blank=True, null=True)),
                ('motivo_interrupcion', models.CharField(blank=True, choices=[('emergencia_laboral', 'Emergencia Laboral'), ('emergencia_familiar', 'Emergencia Familiar'), ('enfermedad', 'Enfermedad'), ('accidente', 'Accidente'), ('otros', 'Otros')], max_length=25, null=True)),
                ('descripcion_interrupcion', models.TextField(blank=True, null=True)),
                ('dias_no_gozados', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('reincorporado', models.BooleanField(default=False)),
                ('fecha_reincorporacion_real', models.DateField(blank=True, null=True)),
                ('observaciones_reincorporacion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goces_vacaciones', to='employees.empleado')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goces_registrados', to=settings.AUTH_USER_MODEL)),
                ('periodo_vacacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goces', to='time_off.periodovacacional')),
                ('solicitud_vacaciones', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goce', to='time_off.solicitudvacaciones')),
            ],
            options={
                'db_table': 'goces_vacaciones',
            },
        ),
        migrations.AddIndex(
            model_name='configuracionvacaciones',
            index=models.Index(fields=['tipo_configuracion'], name='configuraci_tipo_co_b533b1_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionvacaciones',
            index=models.Index(fields=['area'], name='configuraci_area_id_dbfa20_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionvacaciones',
            index=models.Index(fields=['empleado'], name='configuraci_emplead_a45a01_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionvacaciones',
            index=models.Index(fields=['activo'], name='configuraci_activo_26e1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionvacaciones',
            index=models.Index(fields=['fecha_inicio_vigencia'], name='configuraci_fecha_i_899776_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionvacaciones',
            index=models.Index(fields=['fecha_fin_vigencia'], name='configuraci_fecha_f_f8d860_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracionvacaciones',
            unique_together={('tipo_configuracion', 'area', 'empleado', 'fecha_inicio_vigencia')},
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['empleado'], name='periodos_va_emplead_fffe72_idx'),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['contrato'], name='periodos_va_contrat_a5804a_idx'),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['ano_periodo'], name='periodos_va_ano_per_235d09_idx'),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['estado_periodo'], name='periodos_va_estado__f214bd_idx'),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['fecha_vencimiento'], name='periodos_va_fecha_v_c7d330_idx'),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['fecha_inicio_periodo'], name='periodos_va_fecha_i_09f735_idx'),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['fecha_fin_periodo'], name='periodos_va_fecha_f_ba3687_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='periodovacacional',
            unique_together={('empleado', 'ano_periodo', 'contrato')},
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['empleado'], name='solicitudes_emplead_5de986_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['periodo_vacacional'], name='solicitudes_periodo_f089a7_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['estado_solicitud'], name='solicitudes_estado__f20e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['fecha_inicio'], name='solicitudes_fecha_i_4c06b0_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['fecha_fin'], name='solicitudes_fecha_f_39da73_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['fecha_envio'], name='solicitudes_fecha_e_439f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['tipo_solicitud'], name='solicitudes_tipo_so_18daf3_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['aprobado_por_jefe'], name='solicitudes_aprobad_702946_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['aprobado_por_rrhh'], name='solicitudes_aprobad_0a6eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='historialsolicitudvacaciones',
            index=models.Index(fields=['solicitud_vacaciones'], name='historial_s_solicit_e869e6_idx'),
        ),
        migrations.AddIndex(
            model_name='historialsolicitudvacaciones',
            index=models.Index(fields=['tipo_accion'], name='historial_s_tipo_ac_0f74b8_idx'),
        ),
        migrations.AddIndex(
            model_name='historialsolicitudvacaciones',
            index=models.Index(fields=['usuario_accion'], name='historial_s_usuario_a91dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='historialsolicitudvacaciones',
            index=models.Index(fields=['fecha_accion'], name='historial_s_fecha_a_b4c445_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['empleado'], name='goces_vacac_emplead_2c13ce_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['periodo_vacacional'], name='goces_vacac_periodo_27100d_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['estado_goce'], name='goces_vacac_estado__bfafb7_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['fecha_inicio_real'], name='goces_vacac_fecha_i_4c084c_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['fecha_fin_real'], name='goces_vacac_fecha_f_db8eab_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['fecha_reincorporacion'], name='goces_vacac_fecha_r_19d35a_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['reincorporado'], name='goces_vacac_reincor_f3ee2f_idx'),
        ),
    ]
