# Generated by Django 5.2.13 on 2026-05-09 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_tenant_contractamendment_tenant_and_more'),
        ('employees', '0002_alter_academicrecord_unique_together_and_more'),
        ('organization', '0002_company_tenant_department_tenant_and_more'),
        ('tenancy', '0004_supportsession'),
        ('time_off', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vacationconfiguration',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vacationperiod',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vacationconfiguration',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='vacationgrant',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='vacationperiod',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='vacationrequesthistory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='vacationconfiguration',
            unique_together={('tenant', 'tipo_configuracion', 'area', 'empleado', 'fecha_inicio_vigencia')},
        ),
        migrations.AlterUniqueTogether(
            name='vacationperiod',
            unique_together={('tenant', 'empleado', 'ano_periodo', 'contrato')},
        ),
    ]
