# Generated by Django 5.2.13 on 2026-04-27 11:58

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('dni', 'DNI'), ('pasaporte', 'Pasaporte'), ('carnet_extranjeria', 'Carnet de Extranjería'), ('licencia_conducir', 'Licencia de Conducir'), ('certificado_nacimiento', 'Certificado de Nacimiento'), ('certificado_estudios', 'Certificado de Estudios'), ('titulo_profesional', 'Título Profesional'), ('diploma', 'Diploma'), ('certificado_trabajo', 'Certificado de Trabajo'), ('carta_recomendacion', 'Carta de Recomendación'), ('cv', 'Curriculum Vitae'), ('foto', 'Fotografía'), ('certificado_medico', 'Certificado Médico'), ('certificado_antecedentes', 'Certificado de Antecedentes'), ('declaracion_jurada', 'Declaración Jurada'), ('contrato_trabajo', 'Contrato de Trabajo'), ('adenda_contrato', 'Adenda de Contrato'), ('memorandum', 'Memorándum'), ('carta_amonestacion', 'Carta de Amonestación'), ('solicitud_vacaciones', 'Solicitud de Vacaciones'), ('certificado_capacitacion', 'Certificado de Capacitación'), ('evaluacion_desempeno', 'Evaluación de Desempeño'), ('boleta_pago', 'Boleta de Pago'), ('constancia_trabajo', 'Constancia de Trabajo'), ('constancia_participacion', 'Constancia de Participación'), ('constancia_haberes', 'Constancia de Haberes'), ('resolucion_encargatura', 'Resolución de Encargatura'), ('resolucion_licencia', 'Resolución de Licencia'), ('resolucion_sancion', 'Resolución de Sanción'), ('carta_cese', 'Carta de Cese'), ('otros', 'Otros')], max_length=30)),
                ('categoria', models.CharField(choices=[('personal', 'Personal'), ('academico', 'Académico'), ('laboral', 'Laboral'), ('medico', 'Médico'), ('legal', 'Legal'), ('administrativo', 'Administrativo'), ('capacitacion', 'Capacitación'), ('evaluacion', 'Evaluación'), ('remuneraciones', 'Remuneraciones'), ('ubicacion', 'Ubicacion'), ('otros', 'Otros')], max_length=20)),
                ('nombre_documento', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='documentos_empleados/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'rar'])])),
                ('nombre_archivo_original', models.CharField(max_length=255)),
                ('formato_archivo', models.CharField(choices=[('pdf', 'PDF'), ('jpg', 'JPG'), ('jpeg', 'JPEG'), ('png', 'PNG'), ('doc', 'DOC'), ('docx', 'DOCX'), ('xls', 'XLS'), ('xlsx', 'XLSX'), ('txt', 'TXT'), ('zip', 'ZIP'), ('rar', 'RAR')], max_length=10)),
                ('tamano_archivo', models.BigIntegerField(help_text='Tamaño en bytes')),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('entidad_emisora', models.CharField(blank=True, max_length=200, null=True)),
                ('nivel_acceso', models.CharField(choices=[('publico', 'Público'), ('restringido', 'Restringido'), ('confidencial', 'Confidencial'), ('muy_confidencial', 'Muy Confidencial')], default='restringido', max_length=20)),
                ('requiere_autorizacion', models.BooleanField(default=False)),
                ('es_documento_oficial', models.BooleanField(default=False)),
                ('es_copia_certificada', models.BooleanField(default=False)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('es_version_actual', models.BooleanField(default=True)),
                ('estado_documento', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vencido', 'Vencido'), ('pendiente_revision', 'Pendiente de Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('archivado', 'Archivado')], default='activo', max_length=20)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones_validacion', models.TextField(blank=True, null=True)),
                ('fecha_digitalizacion', models.DateTimeField(auto_now_add=True)),
                ('calidad_digitalizacion', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('palabras_clave', models.CharField(blank=True, max_length=500, null=True)),
                ('notas_internas', models.TextField(blank=True, null=True)),
                ('es_confidencial', models.BooleanField(default=False)),
                ('requiere_firma_digital', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'documentos_digitales',
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('certificado_trabajo', 'Certificado de Trabajo'), ('constancia_laboral', 'Constancia Laboral'), ('contrato', 'Contrato'), ('adenda', 'Adenda')], help_text='Tipo de documento que genera esta plantilla', max_length=30)),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la plantilla', max_length=200)),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripcion de la plantilla')),
                ('archivo', models.FileField(help_text='Archivo .docx de la plantilla', upload_to='plantillas_word/%Y/')),
                ('activa', models.BooleanField(default=True, help_text='Si esta plantilla esta disponible para uso')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
            ],
            options={
                'verbose_name': 'Plantilla de Documento',
                'verbose_name_plural': 'Plantillas de Documentos',
                'db_table': 'app_rrhh_plantilla_documento',
                'ordering': ['-created_at'],
            },
        ),
    ]
