# Generated by Django 5.2.13 on 2026-04-26 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosdigitales',
            name='digitalizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_digitalizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentosdigitales',
            name='documento_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='documents.documentosdigitales'),
        ),
        migrations.AddField(
            model_name='documentosdigitales',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_digitales', to='employees.empleado'),
        ),
        migrations.AddField(
            model_name='documentosdigitales',
            name='familiar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='employees.datosfamiliares'),
        ),
        migrations.AddField(
            model_name='documentosdigitales',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentosdigitales',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantilladocumento',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['empleado'], name='documentos__emplead_08c690_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['tipo_documento'], name='documentos__tipo_do_ec317e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['categoria'], name='documentos__categor_6d2a70_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['estado_documento'], name='documentos__estado__45a8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['fecha_vencimiento'], name='documentos__fecha_v_9cee1a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['nivel_acceso'], name='documentos__nivel_a_0d67eb_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['es_version_actual'], name='documentos__es_vers_dbe362_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['fecha_subida'], name='documentos__fecha_s_8a8d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['formato_archivo'], name='documentos__formato_517b26_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['es_documento_oficial'], name='documentos__es_docu_a542c0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['validado_por'], name='documentos__validad_ec3013_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['digitalizado_por'], name='documentos__digital_280aeb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentosdigitales',
            unique_together={('empleado', 'tipo_documento', 'numero_documento', 'version')},
        ),
    ]
