# Generated by Django 5.2.13 on 2026-05-15 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_digitaldocument_tenant_documenttemplate_tenant'),
        ('tenancy', '0004_supportsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signer_name', models.CharField(max_length=200)),
                ('signer_doc_number', models.CharField(max_length=20)),
                ('signer_email', models.EmailField(blank=True, max_length=254)),
                ('kind', models.CharField(choices=[('canvas', 'Trazo manuscrito'), ('checkbox', 'Acuse simple'), ('typed', 'Nombre tipeado')], default='canvas', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('signed', 'Firmada'), ('rejected', 'Rechazada'), ('expired', 'Vencida')], db_index=True, default='requested', max_length=20)),
                ('canvas_base64', models.TextField(blank=True, help_text='base64 PNG payload when kind=canvas')),
                ('typed_name', models.CharField(blank=True, max_length=200)),
                ('checkbox_text', models.CharField(blank=True, max_length=500)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signer_user_agent', models.CharField(blank=True, max_length=400)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.digitaldocument')),
                ('signer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'document_signature',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='document_si_tenant__0e6a27_idx'), models.Index(fields=['document'], name='document_si_documen_5b7a85_idx')],
            },
        ),
    ]
