# Generated by Django 5.2.13 on 2026-05-15 02:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_b10_t_registro_declaration'),
        ('documents', '0004_b10_document_signature'),
        ('employees', '0010_b9_merit_ranking'),
        ('tenancy', '0004_supportsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringDocumentBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Documentos de vinculación', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviado al colaborador'), ('acknowledged', 'Acusado')], db_index=True, default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_bundles', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_bundles', to='employees.employee')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'hiring_document_bundle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HiringBundleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('contrato', 'Contrato'), ('rit', 'Reglamento Interno de Trabajo'), ('reglamento_sst', 'Reglamento Interno de SST'), ('codigo_etica', 'Código de Ética'), ('politica_datos', 'Política de Protección de Datos'), ('manual_funciones', 'Manual de Funciones del Puesto'), ('otro', 'Otro')], max_length=30)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.digitaldocument')),
                ('signature', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_item', to='documents.documentsignature')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.hiringdocumentbundle')),
            ],
            options={
                'db_table': 'hiring_bundle_item',
                'ordering': ['order', 'kind'],
            },
        ),
        migrations.AddIndex(
            model_name='hiringdocumentbundle',
            index=models.Index(fields=['tenant', 'status'], name='hiring_docu_tenant__32951b_idx'),
        ),
        migrations.AddIndex(
            model_name='hiringdocumentbundle',
            index=models.Index(fields=['employee'], name='hiring_docu_employe_0d5835_idx'),
        ),
        migrations.AddConstraint(
            model_name='hiringbundleitem',
            constraint=models.UniqueConstraint(fields=('bundle', 'kind'), name='unique_bundle_kind'),
        ),
    ]
