# Generated by Django 5.2.13 on 2026-05-15 03:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_b10_hiring_bundle'),
        ('employees', '0010_b9_merit_ranking'),
        ('tenancy', '0004_supportsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalDossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_closed', models.BooleanField(db_index=True, default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('retention_until', models.DateField(blank=True, help_text='Fecha mínima de conservación (5 años post-cese).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='digital_dossier', to='employees.employee')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'digital_dossier',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DossierSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('datos_personales', 'Datos personales'), ('datos_academicos', 'Datos académicos'), ('experiencia_laboral', 'Experiencia laboral previa'), ('contratos', 'Contrato vigente y adendas'), ('declaraciones_juradas', 'Declaraciones juradas'), ('identidad_cuspp', 'Documentos de identidad y CUSPP'), ('historial_puestos', 'Historial de puestos ocupados'), ('evaluaciones', 'Evaluaciones de desempeño'), ('capacitaciones', 'Capacitaciones recibidas'), ('reconocimientos', 'Reconocimientos y felicitaciones'), ('sanciones', 'Sanciones disciplinarias'), ('licencias', 'Licencias otorgadas'), ('medicos', 'Exámenes médicos ocupacionales'), ('accidentes', 'Accidentes laborales'), ('cese', 'Documentos de cese')], max_length=30)),
                ('label', models.CharField(max_length=120)),
                ('permission_level', models.PositiveSmallIntegerField(default=3)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='documents.digitaldossier')),
            ],
            options={
                'db_table': 'dossier_section',
                'ordering': ['order', 'kind'],
            },
        ),
        migrations.AddIndex(
            model_name='digitaldossier',
            index=models.Index(fields=['tenant', 'is_closed'], name='digital_dos_tenant__4a8da3_idx'),
        ),
        migrations.AddConstraint(
            model_name='dossiersection',
            constraint=models.UniqueConstraint(fields=('dossier', 'kind'), name='unique_dossier_section_kind'),
        ),
    ]
