# Generated by Django 5.2.13 on 2026-05-15 03:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_b11_probation_period'),
        ('documents', '0006_b12_dossier'),
        ('tenancy', '0004_supportsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaldocument',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_documents', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='digitaldocument',
            name='permission_level',
            field=models.PositiveSmallIntegerField(db_index=True, default=3),
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('preview', 'Preview'), ('print', 'Print'), ('share', 'Share'), ('denied', 'Denied (insufficient permission)')], max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('required_permission_level', models.PositiveSmallIntegerField(default=0)),
                ('user_permission_level', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.digitaldocument')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_access_log',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['document', 'occurred_at'], name='document_ac_documen_a5ee62_idx'), models.Index(fields=['tenant', 'action'], name='document_ac_tenant__6fc71c_idx')],
            },
        ),
    ]
