# Generated by Django 5.2.13 on 2026-05-17 02:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_termination_severancesettlement_severanceline_and_more'),
        ('documents', '0007_b12_access_log_contract_fk'),
        ('employees', '0011_b12_legajo_content'),
        ('tenancy', '0004_supportsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_constancia', models.CharField(help_text='Número correlativo de la constancia', max_length=64)),
                ('fecha_emision', models.DateField()),
                ('cargo_snapshot', models.CharField(blank=True, max_length=200)),
                ('area_snapshot', models.CharField(blank=True, max_length=200)),
                ('fecha_inicio_snapshot', models.DateField(blank=True, null=True)),
                ('fecha_fin_snapshot', models.DateField(blank=True, null=True)),
                ('sueldo_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('motivo_cese_textual', models.TextField(blank=True, help_text='Descripción textual del motivo del cese para el cuerpo')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='cese/constancias_trabajo/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_certificates', to='contracts.contract')),
                ('digital_document', models.OneToOneField(blank=True, help_text='Documento digital adjunto al legajo (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.digitaldocument')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_certificates', to='employees.employee')),
                ('signed_by', models.ForeignKey(blank=True, help_text='Firma del responsable RRHH que emite', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('termination', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='work_certificate', to='contracts.termination')),
            ],
            options={
                'db_table': 'work_certificate',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='work_certif_tenant__0a22d3_idx'), models.Index(fields=['fecha_emision'], name='work_certif_fecha_e_cbcea0_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'numero_constancia'), name='unique_work_certificate_number')],
            },
        ),
    ]
