# Generated by Django 5.2.13 on 2026-05-22 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_b14_work_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentaccesslog',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.digitaldocument'),
        ),
    ]
