# Generated by Django 5.2.13 on 2026-04-27 22:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nombres_usuario', models.CharField(max_length=100)),
                ('apellidos_usuario', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(choices=[('administrador', 'Administrador'), ('rrhh', 'Recursos Humanos'), ('jefe', 'Jefe de Área'), ('empleado', 'Employee'), ('consulta', 'Solo Consulta'), ('invitado', 'Invitado')], max_length=20)),
                ('nivel_acceso', models.CharField(choices=[('total', 'Acceso Total'), ('departamental', 'Acceso Departamental'), ('personal', 'Acceso Personal'), ('limitado', 'Acceso Limitado'), ('lectura', 'Solo Lectura')], default='personal', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('estado_usuario', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido'), ('bloqueado', 'Bloqueado'), ('pendiente', 'Pendiente de Activación')], default='activo', max_length=15)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultimo_cambio_password', models.DateTimeField(blank=True, null=True)),
                ('fecha_expiracion_password', models.DateTimeField(blank=True, null=True)),
                ('requiere_cambio_password', models.BooleanField(default=False)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('fecha_ultimo_intento_fallido', models.DateTimeField(blank=True, null=True)),
                ('fecha_bloqueo', models.DateTimeField(blank=True, null=True)),
                ('token_recuperacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_expiracion_token', models.DateTimeField(blank=True, null=True)),
                ('sesiones_simultaneas_permitidas', models.IntegerField(default=1)),
                ('ip_ultimo_acceso', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_ultimo_acceso', models.TextField(blank=True, null=True)),
                ('recibir_notificaciones_email', models.BooleanField(default=True)),
                ('recibir_notificaciones_sistema', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('created_by', models.ForeignKey(blank=True, db_column='creado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='employees.employee')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_modulo', models.CharField(max_length=100)),
                ('descripcion_modulo', models.TextField(blank=True, null=True)),
                ('icono_modulo', models.CharField(blank=True, max_length=100, null=True)),
                ('ruta_modulo', models.CharField(blank=True, max_length=200, null=True)),
                ('orden_visualizacion', models.IntegerField(default=0)),
                ('estado_modulo', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('permisos_requeridos', models.CharField(blank=True, help_text='Nombres de permisos separados por coma. Vacío = visible para todos los autenticados.', max_length=500, null=True, verbose_name='Permisos requeridos')),
                ('modulo_padre', models.ForeignKey(blank=True, db_column='modulo_padre_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submodulos', to='identity.module', verbose_name='Módulo padre')),
            ],
            options={
                'db_table': 'modulos',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(max_length=100)),
                ('descripcion_permiso', models.TextField(blank=True, null=True)),
                ('modulo', models.CharField(db_column='modulo', help_text='ID del módulo según MODULES_CONFIG (ej: empleados, vacaciones, etc)', max_length=50)),
                ('tipo_permiso', models.CharField(choices=[('crear', 'Crear'), ('leer', 'Leer'), ('actualizar', 'Actualizar'), ('eliminar', 'Eliminar'), ('ejecutar', 'Ejecutar'), ('aprobar', 'Aprobar')], max_length=15)),
                ('estado_permiso', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
            ],
            options={
                'db_table': 'permiso',
                'indexes': [models.Index(fields=['nombre_permiso'], name='permiso_nombre__2dcfd2_idx'), models.Index(fields=['tipo_permiso'], name='permiso_tipo_pe_0017e4_idx'), models.Index(fields=['estado_permiso'], name='permiso_estado__3871a0_idx'), models.Index(fields=['modulo'], name='permiso_modulo_380ffc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('modulo', models.ForeignKey(db_column='modulo_id', on_delete=django.db.models.deletion.CASCADE, related_name='modulo_permisos', to='identity.module')),
                ('permiso', models.ForeignKey(db_column='permiso_id', on_delete=django.db.models.deletion.CASCADE, related_name='modulos_relacionados', to='identity.permission')),
            ],
            options={
                'db_table': 'modulo_permisos',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100, unique=True)),
                ('descripcion_rol', models.TextField(blank=True, null=True)),
                ('nivel_jerarquico', models.IntegerField(default=1)),
                ('es_rol_sistema', models.BooleanField(default=False)),
                ('estado_rol', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
            ],
            options={
                'db_table': 'rol',
                'indexes': [models.Index(fields=['nombre_rol'], name='rol_nombre__f7571c_idx'), models.Index(fields=['estado_rol'], name='rol_estado__d844f1_idx'), models.Index(fields=['nivel_jerarquico'], name='rol_nivel_j_4e26cd_idx'), models.Index(fields=['es_rol_sistema'], name='rol_es_rol__0b5e21_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('asignado_por_usuario', models.ForeignKey(blank=True, db_column='asignado_por_usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to='identity.permission')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_asignados', to='identity.role')),
            ],
            options={
                'db_table': 'rol_permisos',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('estado_asignacion', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido'), ('expirado', 'Expirado')], default='activo', max_length=15)),
                ('asignado_por_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='identity.role')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_roles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='usuarios_usernam_7abab6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='usuarios_email_0ff7b3_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['empleado'], name='usuarios_emplead_0738f0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tipo_usuario'], name='usuarios_tipo_us_3a6d09_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['estado_usuario'], name='usuarios_estado__1a1bda_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['nivel_acceso'], name='usuarios_nivel_a_d11e71_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='usuarios_is_acti_8ee55c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_login'], name='usuarios_last_lo_3c4f79_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='usuarios_date_jo_a5188e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['intentos_fallidos'], name='usuarios_intento_5d60dc_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['fecha_bloqueo'], name='usuarios_fecha_b_242164_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['nombre_modulo'], name='modulos_nombre__ded9d4_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['estado_modulo'], name='modulos_estado__161034_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['orden_visualizacion'], name='modulos_orden_v_d13041_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['modulo_padre', 'estado_modulo', 'orden_visualizacion'], name='modulos_padre_estado_orden_idx'),
        ),
        migrations.AddIndex(
            model_name='modulepermission',
            index=models.Index(fields=['modulo'], name='modulo_perm_modulo__4e2206_idx'),
        ),
        migrations.AddIndex(
            model_name='modulepermission',
            index=models.Index(fields=['permiso'], name='modulo_perm_permiso_2a0908_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modulepermission',
            unique_together={('modulo', 'permiso')},
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['rol'], name='rol_permiso_rol_id_582f08_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permiso'], name='rol_permiso_permiso_c75d67_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['fecha_asignacion'], name='rol_permiso_fecha_a_a51477_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['rol', 'permiso', 'fecha_asignacion'], name='rol_permisos_rol_perm_fec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('rol', 'permiso')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['usuario'], name='usuario_rol_usuario_418f26_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['rol'], name='usuario_rol_rol_id_6b1e29_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['estado_asignacion'], name='usuario_rol_estado__ca8c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['fecha_expiracion'], name='usuario_rol_fecha_e_59d351_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['usuario', 'estado_asignacion'], name='usuario_roles_usr_estado_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('usuario', 'rol')},
        ),
    ]
