# Generated by Django 5.2.13 on 2026-05-09 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('tenancy', '0004_supportsession'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modulepermission',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='modulepermission',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='permission',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='role',
            name='nombre_rol',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='modulepermission',
            unique_together={('tenant', 'modulo', 'permiso')},
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('tenant', 'rol', 'permiso')},
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('tenant', 'usuario', 'rol')},
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre_rol'), name='unique_role_per_tenant'),
        ),
    ]
