# Generated by Django 5.2.13 on 2026-05-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_alter_modulepermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vyntia_staff',
            field=models.BooleanField(db_index=True, default=False, help_text='Vyntia employee with access to the super-admin panel.'),
        ),
    ]
