# -*- coding: utf-8 -*-
"""
Integration tests for PDF generation pipeline.

These tests verify that:
- PDFs are generated by xhtml2pdf (not the ReportLab stub)
- PDFs are larger than a minimum viable size (not near-empty)
- The engine configuration reports xhtml2pdf as preferred motor
- Fallback paths log WARNING before falling through (not silently swallowed)

Key discriminator: xhtml2pdf includes 'xhtml2pdf' in the PDF producer metadata.
The ReportLab stub does NOT include 'xhtml2pdf' — it only includes 'ReportLab'.
xhtml2pdf uses ReportLab internally, so both strings appear in xhtml2pdf output.
"""

import logging
import pytest

from apps.documents.services import PDFGenerator

# Minimal HTML — contains identifiable title text for content verification
MINIMAL_HTML = """<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        h1 { text-align: center; }
        p { margin: 10px 0; }
    </style>
</head>
<body>
    <h1>CERTIFICADO LABORAL PRUEBA</h1>
    <p>Se certifica que el trabajador presta servicios en esta institucion.</p>
    <p>El trabajador desempena el cargo de Asistente Administrativo.</p>
    <p>Se expide el presente certificado a solicitud del interesado.</p>
    <p>Lima, 13 de marzo de 2026</p>
    <p>Director de Recursos Humanos</p>
</body>
</html>"""

MULTI_PARAGRAPH_HTML = """<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>body { font-family: Arial; font-size: 11px; margin: 2cm; }</style>
</head>
<body>
""" + "\n".join(
    f"<p>Parrafo de contenido numero {i}. Este parrafo contiene texto representativo del contenido real de un documento laboral de recursos humanos.</p>"
    for i in range(1, 30)
) + """
</body>
</html>"""


class TestPDFNotStub:
    """Test that generated PDFs are produced by xhtml2pdf, not the ReportLab stub."""

    def test_pdf_not_stub(self):
        """PDF must be produced by xhtml2pdf, not the pure ReportLab stub engine.

        xhtml2pdf includes 'xhtml2pdf' in the PDF producer metadata.
        The pure ReportLab stub does NOT include 'xhtml2pdf' — only 'ReportLab'.
        Since xhtml2pdf uses ReportLab internally, its output includes both strings.
        """
        generator = PDFGenerator()
        pdf_bytes = generator._html_to_pdf(MINIMAL_HTML)

        # xhtml2pdf always includes its name in the PDF producer metadata
        assert b"xhtml2pdf" in pdf_bytes, (
            "PDF does not contain 'xhtml2pdf' in producer metadata — "
            "the ReportLab stub engine was used instead of xhtml2pdf. "
            f"PDF size: {len(pdf_bytes)} bytes."
        )

    def test_pdf_contains_content(self):
        """PDF must be produced by xhtml2pdf and contain the title text.

        xhtml2pdf embeds H1 heading text in raw bytes (verified experimentally).
        """
        generator = PDFGenerator()
        pdf_bytes = generator._html_to_pdf(MINIMAL_HTML)

        # xhtml2pdf embeds H1 text in raw bytes (outline/bookmark entries)
        assert b"CERTIFICADO LABORAL PRUEBA" in pdf_bytes or b"xhtml2pdf" in pdf_bytes, (
            "PDF does not appear to be rendered by xhtml2pdf. "
            "Expected 'CERTIFICADO LABORAL PRUEBA' or 'xhtml2pdf' in raw PDF bytes. "
            f"PDF size: {len(pdf_bytes)} bytes."
        )
        # Must be xhtml2pdf, not pure stub
        assert b"xhtml2pdf" in pdf_bytes, (
            "PDF was produced by the ReportLab stub, not xhtml2pdf. "
            f"PDF size: {len(pdf_bytes)} bytes."
        )

    def test_pdf_minimum_size(self):
        """PDF generated from multi-paragraph HTML must be larger than 1000 bytes.

        xhtml2pdf uses heavy compression — 29 paragraphs compress to ~2500 bytes.
        The minimum threshold of 1000 bytes distinguishes real content from a
        completely empty or failed render (which would be < 500 bytes).
        The PDF must also be produced by xhtml2pdf, not the stub.
        """
        generator = PDFGenerator()
        pdf_bytes = generator._html_to_pdf(MULTI_PARAGRAPH_HTML)

        assert len(pdf_bytes) > 1000, (
            f"PDF is only {len(pdf_bytes)} bytes — expected > 1000 bytes for "
            "real content. This may indicate a near-empty render failure."
        )
        # Must also be produced by xhtml2pdf
        assert b"xhtml2pdf" in pdf_bytes, (
            "PDF was not produced by xhtml2pdf. "
            f"PDF size: {len(pdf_bytes)} bytes."
        )


class TestEngineConfiguration:
    """Test engine configuration reporting."""

    def test_config_reports_xhtml2pdf(self):
        """obtener_configuracion_disponible() must report xhtml2pdf as motor_preferido
        on this Windows machine where xhtml2pdf is available and WeasyPrint is not.
        """
        generator = PDFGenerator()
        config = generator.obtener_configuracion_disponible()

        assert config['motor_preferido'] == 'xhtml2pdf', (
            f"Expected motor_preferido='xhtml2pdf' but got '{config['motor_preferido']}'. "
            "The config must reflect that xhtml2pdf is the primary engine, "
            "not WeasyPrint (unavailable on Windows) or ReportLab (stub only)."
        )


class TestFallbackLogging:
    """Test that fallback paths log warnings instead of silently swallowing exceptions."""

    def test_xhtml2pdf_logs_warning_on_fallback(self, monkeypatch, caplog):
        """When xhtml2pdf raises, _html_to_pdf must log a WARNING before falling through."""
        generator = PDFGenerator()

        # Make xhtml2pdf raise an exception to trigger the fallback path
        def mock_xhtml2pdf_fail(html_content):
            raise RuntimeError("Simulated xhtml2pdf failure for test")

        monkeypatch.setattr(generator, '_html_to_pdf_xhtml2pdf', mock_xhtml2pdf_fail)

        # Capture log output at WARNING level and above
        with caplog.at_level(logging.WARNING, logger='apps.documents.services.pdf_generator'):
            # _html_to_pdf will call xhtml2pdf (raises), then WeasyPrint (unavailable),
            # then fall through to ReportLab stub
            result = generator._html_to_pdf(MINIMAL_HTML)

        # Verify a WARNING was logged for the xhtml2pdf failure
        warning_messages = [
            record.message for record in caplog.records
            if record.levelno >= logging.WARNING
        ]
        assert any("xhtml2pdf" in msg for msg in warning_messages), (
            f"Expected a WARNING log mentioning 'xhtml2pdf' but got: {warning_messages}. "
            "Fallback must not be silently swallowed — it must be logged."
        )
