import {
  Home,
  Users,
  Calendar,
  Building2,
  FileText,
  MapPin,
  Settings,
  Shield,
  UserCheck,
  BarChart3,
  Plus,
  CalendarCheck,
  CalendarDays,
  Briefcase,
  GraduationCap,
  Heart,
  UserCog,
  Key,
  Database,
  Activity,
  Bell,
  Clock,
  DollarSign,
  TrendingUp,
  PieChart,
  Target,
  Award,
  Bookmark,
  CheckCircle,
  AlertCircle,
  Info,
  HelpCircle,
  Search,
  Filter,
  Download,
  Upload,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Mail,
  Phone,
  Globe,
  Folder,
  FolderOpen,
  File,
  Image,
  Video,
  Music,
  Archive,
  Share,
  Copy,
  Scissors,
  Clipboard,
  Save,
  RefreshCw,
  RotateCcw,
  RotateCw,
  ZoomIn,
  ZoomOut,
  Maximize,
  Minimize,
  Menu,
  X,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ExternalLink,
  Link,
  Unlink,
  Star,
  Heart as HeartIcon,
  ThumbsUp,
  ThumbsDown,
  MessageCircle,
  MessageSquare,
  Send,
  Inbox,
  Archive as ArchiveIcon,
  Trash,
  Flag,
  Tag,
  Bookmark as BookmarkIcon,
  Calendar as CalendarIcon,
  Clock as ClockIcon,
  Timer,
  Timer,
  AlarmClock,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  CloudSnow,
  Zap,
  Wifi,
  WifiOff,
  Bluetooth,
  Battery,
  BatteryLow,
  Volume,
  VolumeX,
  Volume1,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Camera,
  CameraOff,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  HardDrive,
  Server,
  Cpu,
  MemoryStick,
  Printer,
  Search,
  Keyboard,
  Mouse,
  Headphones,
  Speaker,
  Gamepad2,
  Joystick,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Spade,
  Club,
  Diamond,
  Heart as HeartSuit,
  Car,
  Truck,
  Bus,
  Bike,
  Plane,
  Train,
  Ship,
  Anchor,
  MapPin as MapPinIcon,
  Map,
  Navigation,
  Compass,
  Route,
  MapPin,
  Construction,
  Hammer,
  Wrench,
  Wrench,
  Paintbrush,
  Palette,
  Brush,
  Scissors,
  Ruler,
  Calculator,
  Abacus,
  Book,
  BookOpen,
  Library,
  Newspaper,
  FileText as FileTextIcon,
  FilePlus,
  FileMinus,
  FileEdit,
  FileCheck,
  FileX,
  Folder as FolderIcon,
  FolderPlus,
  FolderMinus,
  FolderEdit,
  FolderCheck,
  FolderX,
  Package,
  Package2,
  PackageOpen,
  PackageCheck,
  PackageX,
  ShoppingCart,
  ShoppingBag,
  CreditCard,
  Banknote,
  Coins,
  Wallet,
  Receipt,
  PiggyBank,
  TrendingDown,
  BarChart,
  BarChart2,
  BarChart3 as BarChart3Icon,
  LineChart,
  PieChart as PieChartIcon,
  Activity as ActivityIcon,
  Activity,
  Thermometer,
  Gauge,
  Speedometer,
  Tachometer,
  Scale,
  Weight,
  Ruler as RulerIcon,
  Triangle,
  Square,
  Circle,
  Pentagon,
  Hexagon,
  Octagon,
  Star as StarIcon,
  Sparkles,
  Flame,
  Droplet,
  Snowflake,
  Wind,
  Tornado,
  Rainbow,
  Sunrise,
  Sunset,
  Mountain,
  Trees,
  Flower,
  Leaf,
  Leaf,
  Sprout,
  TreePine,
  TreeDeciduous,
  Cactus,
  Mushroom,
  Apple,
  Cherry,
  Grape,
  Orange,
  Banana,
  Strawberry,
  Carrot,
  Corn,
  Wheat,
  Coffee,
  Wine,
  Beer,
  Martini,
  IceCream,
  Cookie,
  Cake,
  Pizza,
  Sandwich,
  Soup,
  Salad,
  Fish,
  Beef,
  Chicken,
  Egg,
  Milk,
  Cheese,
  Bread,
  Croissant,
  Donut,
  Pretzel,
  Popcorn,
  Candy,
  Lollipop,
  Chocolate,
  Honey,
  Salt,
  Pepper,
  Spice,
  Herb,
  Garlic,
  Onion,
  Tomato,
  Potato,
  Avocado,
  Broccoli,
  Lettuce,
  Cabbage,
  Spinach,
  Kale,
  Celery,
  Cucumber,
  Pepper as PepperIcon,
  Chili,
  Ginger,
  Turmeric,
  Cinnamon,
  Vanilla,
  Mint,
  Basil,
  Oregano,
  Thyme,
  Rosemary,
  Sage,
  Parsley,
  Cilantro,
  Dill,
  Fennel,
  Anise,
  Cardamom,
  Clove,
  Nutmeg,
  Allspice,
  BayLeaf,
  Lavender,
  Chamomile,
  Jasmine,
  Rose,
  Tulip,
  Daisy,
  Sunflower,
  Lily,
  Orchid,
  Hibiscus,
  Peony,
  Carnation,
  Chrysanthemum,
  Marigold,
  Pansy,
  Violet,
  Iris,
  Daffodil,
  Hyacinth,
  Crocus,
  Snowdrop,
  Bluebell,
  Poppy,
  Forget
} from 'lucide-react'

/**
 * Mapeo de nombres de iconos del backend a componentes de Lucide React
 */
export const iconMapping: Record<string, any> = {
  // Iconos principales del sistema
  'dashboard': Home,
  'home': Home,
  'users': Users,
  'empleados': Users,
  'calendar': Calendar,
  'vacaciones': Calendar,
  'building': Building2,
  'building2': Building2,
  'areas': Building2,
  'file-text': FileText,
  'boletas': FileText,
  'map-pin': MapPin,
  'ubicaciones': MapPin,
  'settings': Settings,
  'configuracion': Settings,
  'shield': Shield,
  'seguridad': Shield,
  'user-check': UserCheck,
  'usuarios': UserCheck,
  'bar-chart-3': BarChart3,
  'reportes': BarChart3,
  'plus': Plus,
  'nueva': Plus,
  'calendar-check': CalendarCheck,
  'solicitudes': CalendarCheck,
  'calendar-days': CalendarDays,
  'periodos': CalendarDays,
  'briefcase': Briefcase,
  'laborales': Briefcase,
  'graduation-cap': GraduationCap,
  'academicos': GraduationCap,
  'heart': Heart,
  'familiares': Heart,
  'user-cog': UserCog,
  'roles': UserCog,
  'key': Key,
  'permisos': Key,
  
  // Iconos adicionales comunes
  'activity': Activity,
  'bell': Bell,
  'clock': Clock,
  'dollar-sign': DollarSign,
  'trending-up': TrendingUp,
  'pie-chart': PieChart,
  'target': Target,
  'award': Award,
  'bookmark': Bookmark,
  'check-circle': CheckCircle,
  'alert-circle': AlertCircle,
  'info': Info,
  'help-circle': HelpCircle,
  'search': Search,
  'filter': Filter,
  'download': Download,
  'upload': Upload,
  'edit': Edit,
  'trash-2': Trash2,
  'eye': Eye,
  'eye-off': EyeOff,
  'lock': Lock,
  'unlock': Unlock,
  'mail': Mail,
  'phone': Phone,
  'globe': Globe,
  'folder': Folder,
  'folder-open': FolderOpen,
  'file': File,
  'image': Image,
  'video': Video,
  'music': Music,
  'archive': Archive,
  'share': Share,
  'copy': Copy,
  'cut': Scissors,
  'paste': Clipboard,
  'save': Save,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  'maximize': Maximize,
  'minimize': Minimize,
  'menu': Menu,
  'x': X,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'external-link': ExternalLink,
  'link': Link,
  'unlink': Unlink,
  'star': Star,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'send': Send,
  'inbox': Inbox,
  'trash': Trash,
  'flag': Flag,
  'tag': Tag,
  'timer': Timer,
  'stopwatch': Timer,
  'alarm-clock': AlarmClock,
  'sun': Sun,
  'moon': Moon,
  'cloud': Cloud,
  'cloud-rain': CloudRain,
  'cloud-snow': CloudSnow,
  'zap': Zap,
  'wifi': Wifi,
  'wifi-off': WifiOff,
  'bluetooth': Bluetooth,
  'battery': Battery,
  'battery-low': BatteryLow,
  'volume': Volume,
  'volume-off': VolumeX,
  'volume-1': Volume1,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  'mic': Mic,
  'mic-off': MicOff,
  'camera': Camera,
  'camera-off': CameraOff,
  'monitor': Monitor,
  'smartphone': Smartphone,
  'tablet': Tablet,
  'laptop': Laptop,
  'hard-drive': HardDrive,
  'server': Server,
  'cpu': Cpu,
  'memory-stick': MemoryStick,
  'printer': Printer,
  'scanner': Search,
  'keyboard': Keyboard,
  'mouse': Mouse,
  'headphones': Headphones,
  'speaker': Speaker,
  'gamepad-2': Gamepad2,
  'car': Car,
  'truck': Truck,
  'bus': Bus,
  'bike': Bike,
  'plane': Plane,
  'train': Train,
  'ship': Ship,
  'anchor': Anchor,
  'map': Map,
  'navigation': Navigation,
  'compass': Compass,
  'route': Route,
  'road': MapPin,
  'construction': Construction,
  'hammer': Hammer,
  'wrench': Wrench,
  'screwdriver': Wrench,
  'paintbrush': Paintbrush,
  'palette': Palette,
  'brush': Brush,
  'scissors': Scissors,
  'ruler': Ruler,
  'calculator': Calculator,
  'book': Book,
  'book-open': BookOpen,
  'library': Library,
  'newspaper': Newspaper,
  'package': Package,
  'package-2': Package2,
  'package-open': PackageOpen,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  'credit-card': CreditCard,
  'banknote': Banknote,
  'coins': Coins,
  'wallet': Wallet,
  'receipt': Receipt,
  'piggy-bank': PiggyBank,
  'trending-down': TrendingDown,
  'bar-chart': BarChart,
  'bar-chart-2': BarChart2,
  'line-chart': LineChart,
  'pulse': Activity,
  'thermometer': Thermometer,
  'gauge': Gauge,
  'scale': Scale,
  'weight': Weight,
  'triangle': Triangle,
  'square': Square,
  'circle': Circle,
  'sparkles': Sparkles,
  'flame': Flame,
  'droplet': Droplet,
  'snowflake': Snowflake,
  'wind': Wind,
  'rainbow': Rainbow,
  'sunrise': Sunrise,
  'sunset': Sunset,
  'mountain': Mountain,
  'trees': Trees,
  'flower': Flower,
  'leaf': Leaf,
  'seedling': Leaf,
  'database': Database
}

/**
 * Obtiene el componente de icono correspondiente al nombre proporcionado
 * @param iconName Nombre del icono
 * @returns Componente de icono de Lucide React
 */
export const getIcon = (iconName: string) => {
  const normalizedName = iconName?.toLowerCase().replace(/_/g, '-')
  return iconMapping[normalizedName] || Settings // Icono por defecto
}