# Generated by Django 5.2.13 on 2026-05-09 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        ('tenancy', '0004_supportsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingprocess',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
    ]
