# Generated by Django 5.2.13 on 2026-05-15 02:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_b10_t_registro_declaration'),
        ('employees', '0010_b9_merit_ranking'),
        ('onboarding', '0002_onboardingprocess_tenant'),
        ('tenancy', '0004_supportsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InductionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('general', 'General (misión/visión/políticas)'), ('especifica', 'Específica (funciones del puesto)'), ('tecnica', 'Técnica (capacitación específica)'), ('mixed', 'Mixta (general + específica)')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('certified', 'Certificada')], db_index=True, default='draft', max_length=20)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_pdf', models.FileField(blank=True, null=True, upload_to='induccion/certificados/%Y/%m/')),
                ('lengua_originaria', models.CharField(blank=True, help_text='ISO 639-3 code if applicable (SERVIR territorial scope)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='induction_plans', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='induction_plans', to='employees.employee')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'induction_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InductionMentor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='onboarding.inductionplan')),
            ],
            options={
                'db_table': 'induction_mentor',
            },
        ),
        migrations.CreateModel(
            name='InductionEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('competencies', models.JSONField(blank=True, default=dict)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='onboarding.inductionplan')),
            ],
            options={
                'db_table': 'induction_evaluation',
            },
        ),
        migrations.CreateModel(
            name='InductionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('day_1', 'Día 1'), ('first_week', 'Primera semana'), ('first_month', 'Primer mes'), ('ongoing', 'Continua')], default='day_1', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_offset_days', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='onboarding.inductionplan')),
            ],
            options={
                'db_table': 'induction_task',
                'ordering': ['order', 'due_offset_days'],
            },
        ),
        migrations.CreateModel(
            name='InductionMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('format', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('interactive', 'Interactivo'), ('link', 'Enlace externo')], default='pdf', max_length=20)),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='induccion/materiales/%Y/%m/')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='onboarding.inductionplan')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='onboarding.inductiontask')),
            ],
            options={
                'db_table': 'induction_material',
                'ordering': ['plan', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='inductionplan',
            index=models.Index(fields=['tenant', 'status'], name='induction_p_tenant__5625f8_idx'),
        ),
        migrations.AddIndex(
            model_name='inductionplan',
            index=models.Index(fields=['tenant', 'employee'], name='induction_p_tenant__351ccb_idx'),
        ),
    ]
