# Generated by Django 5.2.13 on 2026-05-17 02:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_termination_severancesettlement_severanceline_and_more'),
        ('onboarding', '0003_b11_induction'),
        ('tenancy', '0004_supportsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('skipped', 'Omitida')], db_index=True, default='pending', max_length=15)),
                ('answers', models.JSONField(blank=True, default=dict, help_text='Mapa pregunta_id → respuesta (6 preguntas estándar por defecto)')),
                ('sentiment', models.CharField(blank=True, choices=[('positivo', 'Positivo'), ('neutral', 'Neutral'), ('negativo', 'Negativo'), ('mixto', 'Mixto'), ('no_responde', 'No responde')], max_length=15)),
                ('comments', models.TextField(blank=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('termination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interview', to='contracts.termination')),
            ],
            options={
                'db_table': 'exit_interview',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoverChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_progress', 'En entrega'), ('completed', 'Entrega completada')], db_index=True, default='draft', max_length=15)),
                ('signed_by_outgoing_at', models.DateTimeField(blank=True, null=True)),
                ('signed_by_incoming_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiving_user', models.ForeignKey(blank=True, help_text='Trabajador entrante que recibe el cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signed_by_incoming', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signed_by_outgoing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('termination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover_checklist', to='contracts.termination')),
            ],
            options={
                'db_table': 'handover_checklist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoverItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('proyecto', 'Proyecto en curso'), ('documento', 'Documento / archivo'), ('equipo', 'Equipo / activo físico'), ('acceso', 'Acceso / credencial'), ('credencial', 'Credencial / contraseña'), ('otro', 'Otro')], default='otro', max_length=15)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('no_aplica', 'No aplica')], db_index=True, default='pendiente', max_length=15)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='onboarding.handoverchecklist')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'handover_item',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemsOffboarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En revocación'), ('completed', 'Completado')], db_index=True, default='pending', max_length=15)),
                ('checks', models.JSONField(blank=True, default=dict, help_text='Mapa system_code → bool (completado o no). Default keys: correo, vpn, erp, ad, badge, llaves')),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('termination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='systems_offboarding', to='contracts.termination')),
            ],
            options={
                'db_table': 'systems_offboarding',
                'ordering': ['-created_at'],
            },
        ),
    ]
