# Generated by Django 5.2.13 on 2026-04-26 17:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContratosAdendas',
            fields=[
                ('contrato_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_contrato', models.CharField(help_text='Número del contrato principal', max_length=50)),
                ('numero_adenda', models.CharField(blank=True, help_text='Número de adenda (NULL si es contrato inicial)', max_length=50, null=True)),
                ('tipo_documento', models.CharField(choices=[('CAS_INDETERMINADO', 'CAS a Plazo Indeterminado'), ('CAS_DETERMINADO', 'CAS a Plazo Determinado'), ('CAS_SUPLENCIA', 'CAS a Plazo Determinado Suplencia'), ('LEY_728_FIJO', 'Ley 728 a Plazo Fijo'), ('LEY_728_FIJO_SUPLENCIA', 'Ley 728 a Plazo Fijo Suplencia'), ('LEY_728_INDETERMINADO', 'Ley 728 a Plazo Indeterminado'), ('LEY_276_INDETERMINADO', 'Ley 276 a Plazo Indeterminado'), ('ADENDA_SALARIAL', 'Adenda Salarial'), ('ADENDA_CARGO', 'Adenda de Cambio de Cargo'), ('ADENDA_HORARIO', 'Adenda de Cambio de Horario'), ('ADENDA_EXTENSION', 'Adenda de Extension')], help_text='Tipo de documento contractual', max_length=25)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del contrato/adenda')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de fin del contrato (NULL para indefinidos)', null=True)),
                ('fecha_firma', models.DateField(blank=True, help_text='Fecha de firma del documento', null=True)),
                ('salario_bruto', models.DecimalField(decimal_places=2, help_text='Salario bruto mensual', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('salario_neto', models.DecimalField(blank=True, decimal_places=2, help_text='Salario neto calculado', max_digits=10, null=True)),
                ('cargo', models.CharField(help_text='Cargo o puesto de trabajo', max_length=100)),
                ('jornada_laboral', models.CharField(choices=[('COMPLETA', 'Jornada Completa'), ('PARCIAL', 'Jornada Parcial'), ('REDUCIDA', 'Jornada Reducida'), ('FLEXIBLE', 'Jornada Flexible')], default='COMPLETA', help_text='Tipo de jornada laboral', max_length=15)),
                ('funciones', models.TextField(blank=True, help_text='Descripción de funciones y responsabilidades', null=True)),
                ('lugar_trabajo', models.CharField(blank=True, help_text='Lugar de trabajo', max_length=200, null=True)),
                ('horario_trabajo', models.CharField(blank=True, help_text='Horario de trabajo', max_length=100, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de Firma'), ('ACTIVO', 'Activo'), ('VENCIDO', 'Vencido'), ('TERMINADO', 'Terminado'), ('ANULADO', 'Anulado')], default='BORRADOR', help_text='Estado actual del contrato/adenda', max_length=15)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales', null=True)),
                ('documento_generado', models.BooleanField(default=False, help_text='Indica si se ha generado el documento PDF')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación')),
            ],
            options={
                'verbose_name': 'Contrato/Adenda',
                'verbose_name_plural': 'Contratos/Adendas',
                'db_table': 'contratos_adendas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DatosLaborales',
            fields=[
                ('dato_laboral_id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo_empleado', models.CharField(max_length=100)),
                ('codigo_puesto', models.CharField(blank=True, max_length=20, null=True)),
                ('nivel_puesto', models.CharField(blank=True, max_length=10, null=True)),
                ('categoria', models.CharField(choices=[('directivo', 'Directivo'), ('funcionario', 'Funcionario'), ('profesional', 'Profesional'), ('tecnico', 'Técnico'), ('auxiliar', 'Auxiliar'), ('practicante', 'Practicante'), ('consultor', 'Consultor')], max_length=20)),
                ('tipo_contrato', models.CharField(choices=[('CAS', 'CAS - Contrato Administrativo de Servicios'), ('CAP', 'CAP - Cuadro de Asignación de Personal'), ('indefinido', 'Indefinido'), ('temporal', 'Temporal'), ('practicas', 'Prácticas'), ('consultoria', 'Consultoría'), ('locacion', 'Locación de Servicios')], max_length=20)),
                ('regimen_laboral', models.CharField(choices=[('276', 'Decreto Legislativo 276'), ('728', 'Decreto Legislativo 728'), ('1057', 'Decreto Legislativo 1057 (CAS)'), ('locacion', 'Locación de Servicios'), ('consultoria', 'Consultoría'), ('practicas', 'Prácticas')], max_length=20)),
                ('modalidad_trabajo', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', max_length=15)),
                ('jornada_laboral', models.CharField(choices=[('completa', 'Tiempo Completo'), ('parcial', 'Tiempo Parcial'), ('por_horas', 'Por Horas')], default='completa', max_length=15)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_inicio_contrato', models.DateField()),
                ('fecha_fin_contrato', models.DateField(blank=True, null=True)),
                ('fecha_cese', models.DateField(blank=True, null=True)),
                ('sueldo_basico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asignacion_familiar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('bonificacion_especial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('otras_bonificaciones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('horario_entrada', models.TimeField(blank=True, null=True)),
                ('horario_salida', models.TimeField(blank=True, null=True)),
                ('horas_semanales', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=4)),
                ('estado_datos', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'datos_laborales',
            },
        ),
    ]
