# Generated by Django 5.2.13 on 2026-04-27 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('employees', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='area',
            field=models.ForeignKey(help_text='Área donde se ejecuta el contrato', on_delete=django.db.models.deletion.PROTECT, related_name='contratos_adendas_area', to='organization.department'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='creado_por_id', help_text='User que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='empleado',
            field=models.ForeignKey(help_text='Employee asociado al contrato/adenda', on_delete=django.db.models.deletion.CASCADE, related_name='contratos_adendas', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='modificado_por_id', help_text='User que modificó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='creado_por_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adendas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='parent_contract',
            field=models.ForeignKey(help_text='Contrato padre al que esta adenda modifica', on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='modificado_por_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adendas_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employmentdata',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados_laborales', to='organization.department'),
        ),
        migrations.AddField(
            model_name='employmentdata',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_laborales', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employmentdata',
            name='jefe_directo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados_laborales', to='employees.employee'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['empleado'], name='contratos_a_emplead_74b57c_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['area'], name='contratos_a_area_id_54979d_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['numero_contrato'], name='contratos_a_numero__cf9e10_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['fecha_fin'], name='contratos_a_fecha_f_d8eda3_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='contratos_a_estado_cc42d1_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tipo_documento'], name='contratos_a_tipo_do_81d492_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['fecha_inicio'], name='contratos_a_fecha_i_401979_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['created_by'], name='contratos_a_creado__699081_idx'),
        ),
        migrations.AddIndex(
            model_name='contractamendment',
            index=models.Index(fields=['parent_contract'], name='contract_am_parent__1c852f_idx'),
        ),
        migrations.AddIndex(
            model_name='contractamendment',
            index=models.Index(fields=['tipo_documento'], name='contract_am_tipo_do_4b7bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='contractamendment',
            index=models.Index(fields=['status'], name='contract_am_estado_ff5670_idx'),
        ),
        migrations.AddIndex(
            model_name='contractamendment',
            index=models.Index(fields=['fecha_inicio'], name='contract_am_fecha_i_5c5ca9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractamendment',
            unique_together={('parent_contract', 'numero_adenda')},
        ),
        migrations.AddIndex(
            model_name='employmentdata',
            index=models.Index(fields=['empleado'], name='datos_labor_emplead_330753_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentdata',
            index=models.Index(fields=['area'], name='datos_labor_area_id_3bca69_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentdata',
            index=models.Index(fields=['cargo_empleado'], name='datos_labor_cargo_e_7291e7_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentdata',
            index=models.Index(fields=['tipo_contrato'], name='datos_labor_tipo_co_343446_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentdata',
            index=models.Index(fields=['regimen_laboral'], name='datos_labor_regimen_78f6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentdata',
            index=models.Index(fields=['categoria'], name='datos_labor_categor_874bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentdata',
            index=models.Index(fields=['fecha_ingreso'], name='datos_labor_fecha_i_0a24f0_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentdata',
            index=models.Index(fields=['fecha_inicio_contrato'], name='datos_labor_fecha_i_442f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentdata',
            index=models.Index(fields=['fecha_fin_contrato'], name='datos_labor_fecha_f_2cae45_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentdata',
            index=models.Index(fields=['estado_datos'], name='datos_labor_estado__0c2b88_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentdata',
            index=models.Index(fields=['jefe_directo'], name='datos_labor_jefe_di_9012c4_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentdata',
            index=models.Index(fields=['modalidad_trabajo'], name='datos_labor_modalid_7752a9_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentdata',
            index=models.Index(fields=['jornada_laboral'], name='datos_labor_jornada_3fa2ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employmentdata',
            unique_together={('empleado', 'fecha_inicio_contrato')},
        ),
    ]
