# Generated by Django 5.2.13 on 2026-05-09 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
        ('employees', '0002_alter_academicrecord_unique_together_and_more'),
        ('organization', '0002_company_tenant_department_tenant_and_more'),
        ('tenancy', '0004_supportsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='employmentdata',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='numero_contrato',
            field=models.CharField(help_text='Número del contrato principal', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('tenant', 'numero_contrato'), name='unique_contract_number_per_tenant'),
        ),
    ]
