# Generated by Django 5.2.13 on 2026-05-10 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_tenant_contractamendment_tenant_and_more'),
        ('organization', '0007_b6_plaza_risk_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractamendment',
            name='new_position',
            field=models.ForeignKey(blank=True, help_text='New position FK (post-B.6) for ADENDA_CARGO. Legacy nuevo_cargo preserved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_amendments', to='organization.position'),
        ),
        migrations.AddField(
            model_name='employmentdata',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Catalog position FK (post-B.6). Legacy cargo_empleado preserved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_records', to='organization.position'),
        ),
        migrations.AlterField(
            model_name='contractamendment',
            name='nuevo_cargo',
            field=models.CharField(blank=True, help_text='Nuevo cargo (para ADENDA_CARGO). Legacy string field preserved.', max_length=150, null=True),
        ),
    ]
