# Generated by Django 5.2.13 on 2026-05-15 01:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_b6_position_fk'),
        ('employees', '0010_b9_merit_ranking'),
        ('tenancy', '0004_supportsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TRegistroDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('declaration_type', models.CharField(choices=[('alta', 'Alta'), ('baja', 'Baja'), ('modificacion', 'Modificación')], default='alta', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('validated', 'Validado PVS'), ('submitted', 'Enviado SUNAT'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], db_index=True, default='draft', max_length=20)),
                ('employer_ruc', models.CharField(max_length=11)),
                ('employer_razon_social', models.CharField(max_length=200)),
                ('worker_doc_type', models.CharField(default='01', help_text='SUNAT Tabla 2: 01=DNI 04=CE 07=Pasaporte', max_length=4)),
                ('worker_doc_number', models.CharField(max_length=20)),
                ('worker_apellido_paterno', models.CharField(max_length=80)),
                ('worker_apellido_materno', models.CharField(blank=True, max_length=80)),
                ('worker_nombres', models.CharField(max_length=100)),
                ('worker_birth_date', models.DateField()),
                ('worker_gender', models.CharField(default='M', max_length=1)),
                ('worker_nationality_code', models.CharField(default='604', help_text='ISO 3166 country code (numeric). 604=PER.', max_length=3)),
                ('worker_address', models.CharField(blank=True, max_length=300)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('work_modality_code', models.CharField(help_text='SUNAT modalidad code per Tabla 8', max_length=3)),
                ('occupation_code', models.CharField(blank=True, help_text='CIUO-08 per Tabla 24', max_length=6)),
                ('regimen_laboral_code', models.CharField(default='728', max_length=3)),
                ('regimen_pensionario', models.CharField(choices=[('snp', 'SNP (ONP)'), ('spp', 'SPP (AFP)'), ('decreto_19990', 'DL 19990'), ('decreto_20530', 'DL 20530'), ('sin_regimen', 'Sin régimen')], default='snp', max_length=20)),
                ('pension_provider_code', models.CharField(blank=True, help_text='AFP code if SPP', max_length=10)),
                ('cuspp', models.CharField(blank=True, help_text='CUSPP del trabajador SPP', max_length=20)),
                ('regimen_salud', models.CharField(choices=[('essalud', 'EsSalud'), ('eps', 'EPS'), ('sctr', 'SCTR'), ('ninguno', 'Ninguno')], default='essalud', max_length=20)),
                ('eps_code', models.CharField(blank=True, max_length=10)),
                ('remuneracion_basica', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jornada_horas_semanales', models.PositiveSmallIntegerField(default=48)),
                ('anexo3_txt', models.TextField(blank=True, help_text='Generated Anexo 3 plain text payload')),
                ('pvs_errors', models.JSONField(blank=True, default=list)),
                ('sunat_reference', models.CharField(blank=True, help_text='Número de constancia SUNAT', max_length=64)),
                ('sunat_response_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='t_registro_declarations', to='contracts.contract')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='t_registro_declarations', to='employees.employee')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 't_registro_declaration',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='t_registro__tenant__1715fd_idx'), models.Index(fields=['tenant', 'declaration_type'], name='t_registro__tenant__8526ee_idx'), models.Index(fields=['contract'], name='t_registro__contrac_7c2457_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['submitted', 'accepted'])), fields=('tenant', 'contract', 'declaration_type'), name='unique_active_t_registro_per_contract')],
            },
        ),
    ]
