# Generated by Django 5.2.13 on 2026-05-15 02:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_b10_t_registro_declaration'),
        ('tenancy', '0004_supportsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbationPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regimen', models.CharField(choices=[('728_comun', '728 — Personal común'), ('728_calificado', '728 — Trabajador calificado (con pacto)'), ('728_direccion', '728 — Dirección / Confianza (con pacto)'), ('mype_pequena', 'MYPE Pequeña'), ('276_carrera', '276 — Carrera Administrativa'), ('no_aplica', 'No aplica (CAS u otros)')], default='728_comun', max_length=20)),
                ('plazo_dias', models.PositiveIntegerField(default=90)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente de inicio'), ('in_progress', 'En período de prueba'), ('evaluated', 'Evaluado, pendiente decisión'), ('ratified', 'Ratificado'), ('not_renewed', 'No renovado')], db_index=True, default='pending', max_length=20)),
                ('evaluation_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('evaluation_competencies', models.JSONField(blank=True, default=dict)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='probation_period', to='contracts.contract')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'probation_period',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='probation_p_tenant__732650_idx'), models.Index(fields=['end_date'], name='probation_p_end_dat_528a17_idx')],
            },
        ),
    ]
