# Generated by Django 5.2.13 on 2026-05-17 02:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_b11_probation_period'),
        ('employees', '0011_b12_legajo_content'),
        ('tenancy', '0004_supportsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regimen', models.CharField(choices=[('728', 'D.Leg. 728 LPCL'), ('276', 'D.Leg. 276 carrera administrativa'), ('cas', 'D.L. 1057 CAS'), ('mype', 'MYPE'), ('otros', 'Otros')], default='728', max_length=10)),
                ('causal', models.CharField(choices=[('renuncia', 'Renuncia voluntaria'), ('mutuo_acuerdo', 'Mutuo acuerdo'), ('jubilacion', 'Jubilación'), ('fallecimiento', 'Fallecimiento'), ('despido_justificado', 'Despido justificado (falta grave)'), ('despido_arbitrario', 'Despido arbitrario'), ('despido_indirecto', 'Hostilidad / despido indirecto'), ('vencimiento_plazo', 'Vencimiento del plazo (contrato fijo / CAS)'), ('destitucion', 'Destitución (PAD)'), ('cese_definitivo', 'Cese definitivo'), ('resolucion_anticipada', 'Resolución anticipada CAS'), ('otros', 'Otros')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_progress', 'En trámite'), ('completed', 'Cese completado'), ('liquidated', 'Liquidación pagada'), ('baja_t_registro_done', 'Baja T-Registro realizada'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=30)),
                ('fecha_cese', models.DateField(help_text='Último día con vínculo formal')),
                ('last_day_worked', models.DateField(blank=True, help_text='Último día efectivo trabajado (puede preceder fecha_cese si hubo vacaciones)', null=True)),
                ('motivo', models.TextField(blank=True, help_text='Justificación textual del cese (citar artículo si aplica)')),
                ('carta_renuncia_file', models.FileField(blank=True, null=True, upload_to='cese/cartas_renuncia/%Y/%m/')),
                ('acta_cese_file', models.FileField(blank=True, null=True, upload_to='cese/actas_cese/%Y/%m/')),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('liquidated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baja_t_registro', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termination_baja', to='contracts.tregistrodeclaration')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='termination', to='contracts.contract')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminations', to='employees.employee')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('liquidated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'termination',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeveranceSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('computed', 'Calculada'), ('paid', 'Pagada'), ('void', 'Anulada')], db_index=True, default='draft', max_length=10)),
                ('sueldo_base', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sueldo bruto mensual de referencia (snapshot al cese)', max_digits=12)),
                ('fecha_inicio_contrato', models.DateField(blank=True, null=True)),
                ('fecha_cese', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('manual_override', models.JSONField(blank=True, default=dict, help_text='Overrides manuales por componente (component_code: amount)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('termination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='contracts.termination')),
            ],
            options={
                'db_table': 'severance_settlement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeveranceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component', models.CharField(choices=[('cts', 'CTS proporcional'), ('vac_truncas', 'Vacaciones truncas'), ('grat_trunca', 'Gratificación trunca'), ('indemnizacion', 'Indemnización despido arbitrario'), ('otros', 'Otros / Ajustes manuales')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('base_calculation', models.JSONField(blank=True, default=dict, help_text='Inputs usados para el cómputo (sueldo, días, meses, etc.)')),
                ('formula_note', models.CharField(blank=True, help_text='Descripción textual de la fórmula aplicada', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='contracts.severancesettlement')),
            ],
            options={
                'db_table': 'severance_line',
                'ordering': ['component'],
                'constraints': [models.UniqueConstraint(fields=('settlement', 'component'), name='unique_severance_line_component')],
            },
        ),
        migrations.AddIndex(
            model_name='termination',
            index=models.Index(fields=['tenant', 'status'], name='termination_tenant__874576_idx'),
        ),
        migrations.AddIndex(
            model_name='termination',
            index=models.Index(fields=['tenant', 'causal'], name='termination_tenant__9a99d2_idx'),
        ),
        migrations.AddIndex(
            model_name='termination',
            index=models.Index(fields=['employee'], name='termination_employe_443c75_idx'),
        ),
        migrations.AddIndex(
            model_name='termination',
            index=models.Index(fields=['fecha_cese'], name='termination_fecha_c_a9e91e_idx'),
        ),
        migrations.AddIndex(
            model_name='severancesettlement',
            index=models.Index(fields=['tenant', 'status'], name='severance_s_tenant__3195b3_idx'),
        ),
        migrations.AddIndex(
            model_name='severancesettlement',
            index=models.Index(fields=['paid_at'], name='severance_s_paid_at_207d1a_idx'),
        ),
    ]
