# Generated by Django 5.2.13 on 2026-04-27 11:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Institución Pública', help_text='Nombre de la institución', max_length=300)),
                ('ruc', models.CharField(default='20000000000', help_text='RUC de la institución', max_length=20)),
                ('direccion', models.CharField(default='', help_text='Dirección de la institución', max_length=300)),
                ('distrito', models.CharField(blank=True, default='', max_length=100)),
                ('provincia', models.CharField(blank=True, default='Lima', max_length=100)),
                ('departamento', models.CharField(blank=True, default='Lima', max_length=100)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=150)),
                ('web', models.URLField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, help_text='Logo institucional', null=True, upload_to='empresa/')),
                ('representante_legal', models.CharField(blank=True, default='', help_text='Nombre del representante legal', max_length=200)),
                ('cargo_representante', models.CharField(blank=True, default='', help_text='Cargo del representante', max_length=200)),
                ('dni_representante', models.CharField(blank=True, default='', help_text='DNI del representante', max_length=20)),
                ('resolucion_creacion', models.CharField(blank=True, default='', help_text='Resolución de creación', max_length=200)),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'db_table': 'configuracion_empresa',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_organo', models.CharField(default='SIN ESPECIFICAR', max_length=150)),
                ('nombre_unidad_organica', models.CharField(default='SIN ESPECIFICAR', max_length=150)),
                ('siglas_area', models.CharField(default='TEMP', max_length=20, unique=True)),
                ('descripcion_area', models.TextField(blank=True, null=True)),
                ('jefe_area', models.CharField(blank=True, max_length=150, null=True)),
                ('nivel_jerarquico', models.IntegerField(default=1)),
                ('codigo_presupuestal', models.CharField(blank=True, max_length=20, null=True)),
                ('total_empleados', models.IntegerField(default=0)),
                ('estado_area', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('reestructuracion', 'Reestructuración')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('area_padre', models.ForeignKey(blank=True, db_column='area_padre_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único del registro de ubicación', primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('ingreso', 'Ingreso'), ('traslado', 'Traslado'), ('rotacion', 'Rotación'), ('comision', 'Comisión'), ('destacamento', 'Destacamento'), ('retorno', 'Retorno')], help_text='Tipo de movimiento', max_length=20)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del movimiento')),
                ('fecha_termino', models.DateField(blank=True, help_text='Fecha de término del movimiento', null=True)),
                ('motivo_movimiento', models.TextField(blank=True, help_text='Motivo del movimiento', null=True)),
                ('documento_sustento', models.CharField(blank=True, help_text='Documento que sustenta el movimiento', max_length=100, null=True)),
                ('numero_documento_sustento', models.CharField(blank=True, help_text='Número del documento de sustento', max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales', null=True)),
                ('estado_ubicacion', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('temporal', 'Temporal')], default='activo', help_text='Estado de la ubicación', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_registro', help_text='Fecha de registro')),
                ('area_destino', models.ForeignKey(help_text='ID del área de destino', on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_destino', to='organization.department')),
                ('area_origen', models.ForeignKey(blank=True, help_text='ID del área de origen', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_origen', to='organization.department')),
                ('documento', models.ForeignKey(blank=True, help_text='ID del documento adjunto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones_documento', to='documents.digitaldocument')),
                ('empleado', models.ForeignKey(help_text='ID del empleado', on_delete=django.db.models.deletion.CASCADE, related_name='historial_ubicaciones', to='employees.employee')),
                ('registrado_por_usuario', models.ForeignKey(blank=True, help_text='User que registró el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Ubicación',
                'verbose_name_plural': 'Historial de Ubicaciones',
                'db_table': 'historial_ubicaciones',
                'ordering': ['-fecha_inicio', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['siglas_area'], name='area_siglas__255e90_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['estado_area'], name='area_estado__6d5f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['nombre_organo'], name='area_nombre__c13500_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['area_padre'], name='area_area_pa_1d5a63_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['nivel_jerarquico'], name='area_nivel_j_96d829_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['codigo_presupuestal'], name='area_codigo__b31045_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['total_empleados'], name='area_total_e_4f9815_idx'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['empleado'], name='idx_empleado_id'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['area_origen'], name='idx_area_origen'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['area_destino'], name='idx_area_destino'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['fecha_inicio'], name='idx_fecha_inicio'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['tipo_movimiento'], name='idx_tipo_movimiento'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['estado_ubicacion'], name='historial_u_estado__ac80f1_idx'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['registrado_por_usuario'], name='historial_u_registr_b3b9d2_idx'),
        ),
    ]
