# Generated by Django 5.2.13 on 2026-05-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_company_tenant_department_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='cost_center',
            field=models.CharField(blank=True, db_index=True, help_text='Accounting cost center identifier.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='unit_type',
            field=models.CharField(choices=[('direccion', 'Dirección'), ('gerencia', 'Gerencia'), ('subgerencia', 'Subgerencia'), ('oficina', 'Oficina'), ('area', 'Área'), ('equipo', 'Equipo')], db_index=True, default='area', help_text='Type of organizational unit per Maestro Module 02.', max_length=20),
        ),
    ]
