# Generated by Django 5.2.13 on 2026-05-10 21:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_b6_department_unit_type_cost_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupationalCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Occupational Category',
                'verbose_name_plural': 'Occupational Categories',
                'db_table': 'occupational_category',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CIUOCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('big_group', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CIUO Code',
                'verbose_name_plural': 'CIUO Codes',
                'db_table': 'ciuo_code',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['big_group'], name='ciuo_code_big_gro_761bc3_idx'), models.Index(fields=['is_active'], name='ciuo_code_is_acti_1b231c_idx')],
            },
        ),
    ]
