# Generated by Django 5.2.13 on 2026-05-10 21:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_b6_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionFunction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('is_primary', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='organization.position')),
            ],
            options={
                'db_table': 'position_function',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PositionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mission', models.TextField(blank=True)),
                ('technical_competencies', models.JSONField(blank=True, default=list)),
                ('soft_competencies', models.JSONField(blank=True, default=list)),
                ('work_conditions', models.TextField(blank=True)),
                ('kpis', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='organization.position')),
            ],
            options={
                'db_table': 'position_profile',
            },
        ),
        migrations.CreateModel(
            name='PositionRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('education', 'Educación'), ('experience', 'Experiencia'), ('language', 'Idioma'), ('certification', 'Certificación'), ('other', 'Otro')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='organization.position')),
            ],
            options={
                'db_table': 'position_requirement',
                'ordering': ['kind', 'id'],
                'indexes': [models.Index(fields=['position', 'kind'], name='position_re_positio_cc568d_idx')],
            },
        ),
    ]
