# Generated by Django 5.2.13 on 2026-05-10 21:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_correo_personal_and_more'),
        ('organization', '0006_b6_position_profile'),
        ('tenancy', '0004_supportsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionRiskProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_level', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('very_high', 'Muy alto')], default='low', max_length=20)),
                ('risk_factors', models.JSONField(blank=True, default=list, help_text='Placeholder for SST module M07 — list of risk-factor tags.')),
                ('notes', models.TextField(blank=True)),
                ('requires_medical_exam', models.BooleanField(default=False)),
                ('requires_iperc', models.BooleanField(default=False, help_text='IPERC = Identificación de Peligros, Evaluación de Riesgos y Control.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to='organization.position')),
            ],
            options={
                'db_table': 'position_risk_profile',
            },
        ),
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('vacante', 'Vacante'), ('ocupada', 'Ocupada'), ('congelada', 'Congelada'), ('eliminada', 'Eliminada')], db_index=True, default='vacante', max_length=20)),
                ('opened_at', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plazas', to='employees.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plazas', to='organization.position')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'plaza',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='plaza_tenant__650b32_idx'), models.Index(fields=['position', 'status'], name='plaza_positio_0e71fe_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='unique_plaza_code_per_tenant')],
            },
        ),
    ]
