# Generated by Django 5.2.13 on 2026-05-10 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0003_b7_factor_score_salary_band'),
        ('organization', '0007_b6_plaza_risk_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Ley 30709 category from CCF (post-B.7). Nullable while CCF rolls out.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='compensation.category'),
        ),
    ]
