# Generated by Django 5.2.13 on 2026-05-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_b7_position_category_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='familia_puesto',
            field=models.CharField(blank=True, help_text='SERVIR familia de puestos (agrupación temática).', max_length=100),
        ),
        migrations.AddField(
            model_name='position',
            name='salary_tier',
            field=models.CharField(blank=True, choices=[('principal', 'Principal'), ('ajustada', 'Ajustada'), ('priorizada', 'Priorizada')], help_text='D.S. 138-2014-EF compensación principal / ajustada / priorizada.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='servir_group',
            field=models.CharField(blank=True, choices=[('fp', 'Funcionario Público'), ('dp', 'Directivo Público'), ('cc', 'Servidor Civil de Carrera'), ('cs', 'Servidor de Actividades Complementarias'), ('cf', 'Servidor de Confianza')], db_index=True, help_text='Ley 30057 grupo de servidor civil. Solo para tenants sector público.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='servir_level',
            field=models.CharField(blank=True, choices=[('cf_1', 'CF-1 (Inicial)'), ('cf_2', 'CF-2 (Intermedio)'), ('cf_3', 'CF-3 (Avanzado)'), ('cf_4', 'CF-4 (Senior)'), ('dp_1', 'DP-1'), ('dp_2', 'DP-2'), ('dp_3', 'DP-3'), ('dp_4', 'DP-4')], help_text='Nivel SERVIR para servidor de carrera o directivo público.', max_length=10, null=True),
        ),
    ]
