# Generated by Django 5.2.13 on 2026-05-11 00:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_b8_position_servir_fields'),
        ('tenancy', '0004_supportsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('register_type', models.CharField(choices=[('cpe', 'Cuadro de Puestos de la Entidad (Ley 30057 SERVIR)'), ('cap', 'Cuadro de Asignación de Personal (DL 276/728)')], db_index=True, max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('approved', 'Aprobado'), ('registered_servir', 'Registrado SERVIR'), ('superseded', 'Reemplazado'), ('archived', 'Archivado')], db_index=True, default='draft', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('servir_registered_at', models.DateTimeField(blank=True, null=True)),
                ('servir_registration_ref', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='organization.positionregister')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'position_register',
                'ordering': ['-effective_date', '-version'],
            },
        ),
        migrations.CreateModel(
            name='PositionRegisterEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('plaza_code', models.CharField(blank=True, max_length=30)),
                ('plaza_count', models.PositiveIntegerField(default=1)),
                ('situacion', models.CharField(choices=[('ocupada', 'Ocupada'), ('vacante', 'Vacante'), ('prevista', 'Prevista')], default='vacante', max_length=20)),
                ('nivel_organizacional', models.CharField(blank=True, max_length=100)),
                ('nivel_remunerativo', models.CharField(blank=True, max_length=50)),
                ('clasificacion_cap', models.CharField(blank=True, choices=[('fp', 'FP - Funcionario Público'), ('ec', 'EC - Empleado de Confianza'), ('sp_ds', 'SP-DS - Directivo Superior'), ('sp_ej', 'SP-EJ - Ejecutivo'), ('sp_es', 'SP-ES - Especialista'), ('sp_ap', 'SP-AP - Apoyo'), ('re', 'RE - Régimen Especial')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_entries', to='organization.position')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='organization.positionregister')),
            ],
            options={
                'db_table': 'position_register_entry',
                'ordering': ['register', 'sequence', 'plaza_code'],
            },
        ),
        migrations.AddIndex(
            model_name='positionregister',
            index=models.Index(fields=['tenant', 'register_type', 'status'], name='position_re_tenant__0fc1e2_idx'),
        ),
        migrations.AddIndex(
            model_name='positionregister',
            index=models.Index(fields=['tenant', 'register_type', 'version'], name='position_re_tenant__cc6b9f_idx'),
        ),
        migrations.AddConstraint(
            model_name='positionregister',
            constraint=models.UniqueConstraint(fields=('tenant', 'register_type', 'title', 'version'), name='unique_position_register_title_version_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='positionregisterentry',
            index=models.Index(fields=['register', 'sequence'], name='position_re_registe_a795c4_idx'),
        ),
        migrations.AddIndex(
            model_name='positionregisterentry',
            index=models.Index(fields=['position'], name='position_re_positio_584666_idx'),
        ),
    ]
