# Generated by Django 5.2.13 on 2026-05-15 05:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_b12_legajo_content'),
        ('organization', '0010_b8_position_register'),
        ('tenancy', '0004_supportsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Displacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('rotacion', 'Rotación'), ('encargatura', 'Encargatura'), ('destaque', 'Destaque'), ('comision', 'Comisión de servicios'), ('designacion', 'Designación'), ('transferencia', 'Transferencia'), ('permuta', 'Permuta')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending_supervisor', 'Pendiente jefe directo'), ('pending_hr', 'Pendiente RRHH'), ('pending_titular', 'Pendiente titular'), ('approved', 'Aprobado'), ('active', 'En ejecución'), ('completed', 'Concluido'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=20)),
                ('destino_entidad_externa', models.CharField(blank=True, help_text='Razón social de la entidad destino si el desplazamiento es externo', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('justification', models.TextField(blank=True)),
                ('resolution_number', models.CharField(blank=True, help_text='Número de resolución administrativa (opaco; puede generarse externamente)', max_length=64)),
                ('approved_by_supervisor_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_hr_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_titular_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_pdf', models.FileField(blank=True, null=True, upload_to='desplazamiento/resoluciones/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_hr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approved_by_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approved_by_titular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destino_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='displacements_destino', to='organization.department')),
                ('destino_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.position')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='displacements', to='employees.employee')),
                ('origen_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='displacements_origen', to='organization.department')),
                ('origen_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.position')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'displacement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisplacementExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_end_date', models.DateField()),
                ('new_end_date', models.DateField()),
                ('reason', models.TextField()),
                ('resolution_number', models.CharField(blank=True, max_length=64)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('displacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='organization.displacement')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'displacement_extension',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='displacement',
            index=models.Index(fields=['tenant', 'status'], name='displacemen_tenant__23839e_idx'),
        ),
        migrations.AddIndex(
            model_name='displacement',
            index=models.Index(fields=['tenant', 'kind'], name='displacemen_tenant__61c62c_idx'),
        ),
        migrations.AddIndex(
            model_name='displacement',
            index=models.Index(fields=['employee'], name='displacemen_employe_1f9025_idx'),
        ),
    ]
