# Generated by Django 5.2.13 on 2026-05-10 22:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('competencias', 'Competencias'), ('responsabilidad', 'Responsabilidad'), ('esfuerzo', 'Esfuerzo'), ('condiciones', 'Condiciones de Trabajo')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='% weight of this factor (sums to 100 across all 4).', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_factor',
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='JobSubfactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_score', models.PositiveIntegerField(default=100, help_text='Maximum allowed score for this subfactor on any Category.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfactors', to='compensation.jobfactor')),
            ],
            options={
                'db_table': 'job_subfactor',
                'ordering': ['factor', 'code'],
                'indexes': [models.Index(fields=['factor', 'is_active'], name='job_subfact_factor__d06630_idx')],
            },
        ),
    ]
