# Generated by Django 5.2.13 on 2026-05-10 22:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0001_b7_job_factor'),
        ('tenancy', '0004_supportsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFunctionTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('approved', 'Aprobado'), ('superseded', 'Reemplazado'), ('archived', 'Archivado')], db_index=True, default='draft', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ccfs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ccfs', to=settings.AUTH_USER_MODEL)),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='compensation.categoryfunctiontable')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'category_function_table',
                'ordering': ['-effective_date', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('functions_summary', models.TextField(blank=True, help_text='Funciones generales de la categoría (Ley 30709 § 4.1).')),
                ('min_education', models.CharField(blank=True, max_length=200)),
                ('min_experience_years', models.PositiveIntegerField(default=0)),
                ('technical_competencies', models.JSONField(blank=True, default=list)),
                ('soft_competencies', models.JSONField(blank=True, default=list)),
                ('physical_conditions', models.TextField(blank=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total puntaje (computed from CategoryFactorScore × JobFactor.weight).', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('ccf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='compensation.categoryfunctiontable')),
            ],
            options={
                'db_table': 'compensation_category',
                'ordering': ['ccf', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='categoryfunctiontable',
            index=models.Index(fields=['tenant', 'status'], name='category_fu_tenant__c58de0_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryfunctiontable',
            index=models.Index(fields=['tenant', 'version'], name='category_fu_tenant__a17734_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoryfunctiontable',
            constraint=models.UniqueConstraint(fields=('tenant', 'title', 'version'), name='unique_ccf_title_version_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'ccf'], name='compensatio_tenant__3b372f_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['ccf', 'is_active'], name='compensatio_ccf_id_71f2e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('tenant', 'ccf', 'code'), name='unique_category_code_per_ccf_per_tenant'),
        ),
    ]
