# Generated by Django 5.2.13 on 2026-05-10 22:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0002_b7_ccf_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mid_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('placement_criteria', models.TextField(blank=True, help_text='Criterios para ubicar al trabajador en la banda (experiencia, desempeño, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_band', to='compensation.category')),
            ],
            options={
                'db_table': 'salary_band',
            },
        ),
        migrations.CreateModel(
            name='CategoryFactorScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(default=0, help_text='Score 0..subfactor.max_score.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_scores', to='compensation.category')),
                ('subfactor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='compensation.jobsubfactor')),
            ],
            options={
                'db_table': 'category_factor_score',
                'ordering': ['category', 'subfactor'],
                'constraints': [models.UniqueConstraint(fields=('category', 'subfactor'), name='unique_factor_score_per_category_subfactor')],
            },
        ),
    ]
