# Generated by Django 5.2.13 on 2026-04-26 17:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionVacaciones',
            fields=[
                ('configuracion_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_configuracion', models.CharField(choices=[('general', 'General'), ('area', 'Por Área'), ('empleado', 'Por Empleado'), ('cargo', 'Por Cargo')], max_length=15)),
                ('dias_por_ano', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('dias_adicionales_antiguedad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('anos_para_adicional', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('permite_acumulacion', models.BooleanField(default=True)),
                ('max_dias_acumulables', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)])),
                ('dias_minimos_solicitud', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('dias_maximos_solicitud', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('dias_anticipacion_minima', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)])),
                ('tipo_calculo', models.CharField(choices=[('dias_calendario', 'Días Calendario'), ('dias_habiles', 'Días Hábiles'), ('proporcional', 'Proporcional')], default='dias_calendario', max_length=20)),
                ('incluye_feriados', models.BooleanField(default=True)),
                ('incluye_fines_semana', models.BooleanField(default=True)),
                ('requiere_aprobacion_jefe', models.BooleanField(default=True)),
                ('requiere_aprobacion_rrhh', models.BooleanField(default=True)),
                ('niveles_aprobacion', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('permite_fraccionamiento', models.BooleanField(default=True)),
                ('min_dias_por_fraccion', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('max_fracciones_por_ano', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio_vigencia', models.DateField()),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'configuracion_vacaciones',
            },
        ),
        migrations.CreateModel(
            name='GoceVacaciones',
            fields=[
                ('goce_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio_real', models.DateField()),
                ('fecha_fin_real', models.DateField()),
                ('fecha_reincorporacion', models.DateField(blank=True, null=True)),
                ('dias_gozados', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('365.0'))])),
                ('estado_goce', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('interrumpido', 'Interrumpido'), ('cancelado', 'Cancelado')], default='programado', max_length=15)),
                ('fecha_interrupcion', models.DateField(blank=True, null=True)),
                ('motivo_interrupcion', models.CharField(blank=True, choices=[('emergencia_laboral', 'Emergencia Laboral'), ('emergencia_familiar', 'Emergencia Familiar'), ('enfermedad', 'Enfermedad'), ('accidente', 'Accidente'), ('otros', 'Otros')], max_length=25, null=True)),
                ('descripcion_interrupcion', models.TextField(blank=True, null=True)),
                ('dias_no_gozados', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('reincorporado', models.BooleanField(default=False)),
                ('fecha_reincorporacion_real', models.DateField(blank=True, null=True)),
                ('observaciones_reincorporacion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'goces_vacaciones',
            },
        ),
        migrations.CreateModel(
            name='HistorialSolicitudVacaciones',
            fields=[
                ('historial_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_accion', models.CharField(choices=[('creacion', 'Creación'), ('envio', 'Envío'), ('aprobacion_jefe', 'Aprobación Jefe'), ('aprobacion_rrhh', 'Aprobación RRHH'), ('rechazo', 'Rechazo'), ('cancelacion', 'Cancelación'), ('modificacion', 'Modificación'), ('inicio_goce', 'Inicio de Goce'), ('fin_goce', 'Fin de Goce'), ('interrupcion', 'Interrupción'), ('reincorporacion', 'Reincorporación')], max_length=20)),
                ('descripcion_accion', models.TextField()),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('datos_adicionales', models.JSONField(blank=True, null=True)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historial_solicitudes_vacaciones',
            },
        ),
        migrations.CreateModel(
            name='OnboardingEmpleado',
            fields=[
                ('onboarding_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_onboarding', models.CharField(choices=[('pendiente_datos', 'Pendiente de Datos Personales'), ('pendiente_documentos', 'Pendiente de Documentos'), ('pendiente_validacion', 'Pendiente de Validacion RRHH'), ('observado', 'Observado - Requiere Correccion'), ('completado', 'Completado')], default='pendiente_datos', max_length=25)),
                ('datos_personales_completos', models.BooleanField(default=False)),
                ('datos_laborales_completos', models.BooleanField(default=False)),
                ('dni_subido', models.BooleanField(default=False)),
                ('declaraciones_juradas_subidas', models.BooleanField(default=False)),
                ('certificados_academicos_subidos', models.BooleanField(default=False)),
                ('certificados_trabajo_subidos', models.BooleanField(default=False)),
                ('documentos_familiares_subidos', models.BooleanField(default=False)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('email_bienvenida_enviado', models.BooleanField(default=False)),
                ('fecha_email_bienvenida', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'onboarding_empleado',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoVacacional',
            fields=[
                ('periodo_id', models.AutoField(primary_key=True, serialize=False)),
                ('ano_periodo', models.IntegerField()),
                ('fecha_inicio_periodo', models.DateField()),
                ('fecha_fin_periodo', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('dias_correspondientes', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('365.0'))])),
                ('dias_adicionales', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('30.0'))])),
                ('dias_totales', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('365.0'))])),
                ('dias_gozados', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('dias_pendientes', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('dias_vencidos', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('estado_periodo', models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='activo', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'periodos_vacacionales',
            },
        ),
        migrations.CreateModel(
            name='SolicitudVacaciones',
            fields=[
                ('solicitud_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_solicitud', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('adelanto_vacaciones', 'Adelanto de Vacaciones'), ('fraccionamiento', 'Fraccionamiento'), ('postergacion', 'Postergación')], default='vacaciones', max_length=25)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_solicitados', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('365.0'))])),
                ('medio_dia', models.BooleanField(default=False)),
                ('motivo_solicitud', models.TextField()),
                ('observaciones_empleado', models.TextField(blank=True, null=True)),
                ('estado_solicitud', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('en_revision', 'En Revisión'), ('aprobada_jefe', 'Aprobada por Jefe'), ('aprobada_rrhh', 'Aprobada por RRHH'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('en_goce', 'En Goce'), ('finalizada', 'Finalizada')], default='borrador', max_length=20)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por_jefe', models.BooleanField(default=False)),
                ('fecha_aprobacion_jefe', models.DateTimeField(blank=True, null=True)),
                ('observaciones_jefe', models.TextField(blank=True, null=True)),
                ('aprobado_por_rrhh', models.BooleanField(default=False)),
                ('fecha_aprobacion_rrhh', models.DateTimeField(blank=True, null=True)),
                ('observaciones_rrhh', models.TextField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('fecha_rechazo', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'solicitudes_vacaciones',
            },
        ),
    ]
