# Generated by Django 5.2.13 on 2026-04-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingEmpleado',
            fields=[
                ('onboarding_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_onboarding', models.CharField(choices=[('pendiente_datos', 'Pendiente de Datos Personales'), ('pendiente_documentos', 'Pendiente de Documentos'), ('pendiente_validacion', 'Pendiente de Validacion RRHH'), ('observado', 'Observado - Requiere Correccion'), ('completado', 'Completado')], default='pendiente_datos', max_length=25)),
                ('datos_personales_completos', models.BooleanField(default=False)),
                ('datos_laborales_completos', models.BooleanField(default=False)),
                ('dni_subido', models.BooleanField(default=False)),
                ('declaraciones_juradas_subidas', models.BooleanField(default=False)),
                ('certificados_academicos_subidos', models.BooleanField(default=False)),
                ('certificados_trabajo_subidos', models.BooleanField(default=False)),
                ('documentos_familiares_subidos', models.BooleanField(default=False)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('email_bienvenida_enviado', models.BooleanField(default=False)),
                ('fecha_email_bienvenida', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'onboarding_empleado',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
