# Generated by Django 4.2.23 on 2025-09-03 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='permiso',
            name='permiso_modulo__e0d3af_idx',
        ),
        migrations.RemoveField(
            model_name='permiso',
            name='modulo_id',
        ),
        migrations.AddField(
            model_name='permiso',
            name='modulo',
            field=models.ForeignKey(db_column='modulo_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='app_rrhh.modulos'),
        ),
        migrations.AlterField(
            model_name='area',
            name='estado_area',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('reestructuracion', 'Reestructuración')], default='activo', max_length=20),
        ),
        migrations.AddIndex(
            model_name='permiso',
            index=models.Index(fields=['modulo'], name='permiso_modulo__e0d3af_idx'),
        ),
    ]
