# Generated by Django 5.2.13 on 2026-04-26 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_rrhh', '0001_initial'),
        ('contracts', '0001_initial'),
        ('employees', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionvacaciones',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_vacaciones', to='organization.area'),
        ),
        migrations.AddField(
            model_name='configuracionvacaciones',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_vacaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracionvacaciones',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_vacaciones', to='employees.empleado'),
        ),
        migrations.AddField(
            model_name='gocevacaciones',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goces_vacaciones', to='employees.empleado'),
        ),
        migrations.AddField(
            model_name='gocevacaciones',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goces_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialsolicitudvacaciones',
            name='usuario_accion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_vacaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingempleado',
            name='empleado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='employees.empleado'),
        ),
        migrations.AddField(
            model_name='onboardingempleado',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingempleado',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboardings_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periodovacacional',
            name='configuracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos', to='app_rrhh.configuracionvacaciones'),
        ),
        migrations.AddField(
            model_name='periodovacacional',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periodos_vacacionales', to='contracts.contratosadendas'),
        ),
        migrations.AddField(
            model_name='periodovacacional',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_vacacionales_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periodovacacional',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_vacacionales', to='employees.empleado'),
        ),
        migrations.AddField(
            model_name='gocevacaciones',
            name='periodo_vacacional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goces', to='app_rrhh.periodovacacional'),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_vacaciones', to='employees.empleado'),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='jefe_aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas_como_jefe', to='employees.empleado'),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='periodo_vacacional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='app_rrhh.periodovacacional'),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='rechazado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_rechazadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='rrhh_aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas_rrhh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialsolicitudvacaciones',
            name='solicitud_vacaciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='app_rrhh.solicitudvacaciones'),
        ),
        migrations.AddField(
            model_name='gocevacaciones',
            name='solicitud_vacaciones',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goce', to='app_rrhh.solicitudvacaciones'),
        ),
        migrations.AddIndex(
            model_name='configuracionvacaciones',
            index=models.Index(fields=['tipo_configuracion'], name='configuraci_tipo_co_b533b1_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionvacaciones',
            index=models.Index(fields=['area'], name='configuraci_area_id_dbfa20_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionvacaciones',
            index=models.Index(fields=['empleado'], name='configuraci_emplead_a45a01_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionvacaciones',
            index=models.Index(fields=['activo'], name='configuraci_activo_26e1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionvacaciones',
            index=models.Index(fields=['fecha_inicio_vigencia'], name='configuraci_fecha_i_899776_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionvacaciones',
            index=models.Index(fields=['fecha_fin_vigencia'], name='configuraci_fecha_f_f8d860_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracionvacaciones',
            unique_together={('tipo_configuracion', 'area', 'empleado', 'fecha_inicio_vigencia')},
        ),
        migrations.AddIndex(
            model_name='onboardingempleado',
            index=models.Index(fields=['estado_onboarding'], name='onboarding__estado__d9cfa9_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingempleado',
            index=models.Index(fields=['empleado'], name='onboarding__emplead_f3f95c_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingempleado',
            index=models.Index(fields=['usuario'], name='onboarding__usuario_3e937e_idx'),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['empleado'], name='periodos_va_emplead_fffe72_idx'),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['contrato'], name='periodos_va_contrat_a5804a_idx'),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['ano_periodo'], name='periodos_va_ano_per_235d09_idx'),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['estado_periodo'], name='periodos_va_estado__f214bd_idx'),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['fecha_vencimiento'], name='periodos_va_fecha_v_c7d330_idx'),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['fecha_inicio_periodo'], name='periodos_va_fecha_i_09f735_idx'),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['fecha_fin_periodo'], name='periodos_va_fecha_f_ba3687_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='periodovacacional',
            unique_together={('empleado', 'ano_periodo', 'contrato')},
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['empleado'], name='solicitudes_emplead_5de986_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['periodo_vacacional'], name='solicitudes_periodo_f089a7_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['estado_solicitud'], name='solicitudes_estado__f20e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['fecha_inicio'], name='solicitudes_fecha_i_4c06b0_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['fecha_fin'], name='solicitudes_fecha_f_39da73_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['fecha_envio'], name='solicitudes_fecha_e_439f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['tipo_solicitud'], name='solicitudes_tipo_so_18daf3_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['aprobado_por_jefe'], name='solicitudes_aprobad_702946_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['aprobado_por_rrhh'], name='solicitudes_aprobad_0a6eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='historialsolicitudvacaciones',
            index=models.Index(fields=['solicitud_vacaciones'], name='historial_s_solicit_e869e6_idx'),
        ),
        migrations.AddIndex(
            model_name='historialsolicitudvacaciones',
            index=models.Index(fields=['tipo_accion'], name='historial_s_tipo_ac_0f74b8_idx'),
        ),
        migrations.AddIndex(
            model_name='historialsolicitudvacaciones',
            index=models.Index(fields=['usuario_accion'], name='historial_s_usuario_a91dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='historialsolicitudvacaciones',
            index=models.Index(fields=['fecha_accion'], name='historial_s_fecha_a_b4c445_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['empleado'], name='goces_vacac_emplead_2c13ce_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['periodo_vacacional'], name='goces_vacac_periodo_27100d_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['estado_goce'], name='goces_vacac_estado__bfafb7_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['fecha_inicio_real'], name='goces_vacac_fecha_i_4c084c_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['fecha_fin_real'], name='goces_vacac_fecha_f_db8eab_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['fecha_reincorporacion'], name='goces_vacac_fecha_r_19d35a_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['reincorporado'], name='goces_vacac_reincor_f3ee2f_idx'),
        ),
    ]
