# Generated by Django 5.2.13 on 2026-04-26 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_rrhh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendariopago',
            name='usuario_programacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendarios_programados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='configuracionafp',
            index=models.Index(fields=['afp_nombre'], name='configuraci_afp_nom_8564da_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionafp',
            index=models.Index(fields=['vigencia_mes'], name='configuraci_vigenci_12071c_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionafp',
            index=models.Index(fields=['estado'], name='configuraci_estado_34bdb1_idx'),
        ),
        migrations.AddConstraint(
            model_name='configuracionafp',
            constraint=models.UniqueConstraint(fields=('afp_nombre', 'vigencia_mes'), name='uniq_config_afp_nombre_vigencia'),
        ),
        migrations.AddIndex(
            model_name='configuracionremuneracion',
            index=models.Index(fields=['tipo'], name='configuraci_tipo_48de49_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionremuneracion',
            index=models.Index(fields=['codigo'], name='configuraci_codigo_2938f0_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionremuneracion',
            index=models.Index(fields=['estado'], name='configuraci_estado_d391c8_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionremuneracion',
            index=models.Index(fields=['orden'], name='configuraci_orden_eb4d3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='configuracionremuneracion',
            constraint=models.UniqueConstraint(fields=('tipo', 'codigo'), name='uniq_config_remuneracion_tipo_codigo'),
        ),
        migrations.AddField(
            model_name='conceptoplanilla',
            name='configuracion_concepto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_planilla', to='app_rrhh.configuracionremuneracion'),
        ),
        migrations.AddField(
            model_name='configuracionuit',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_uit_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracionvacaciones',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_vacaciones', to='app_rrhh.area'),
        ),
        migrations.AddField(
            model_name='configuracionvacaciones',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_vacaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratosadendas',
            name='area',
            field=models.ForeignKey(help_text='Área donde se ejecuta el contrato', on_delete=django.db.models.deletion.PROTECT, related_name='contratos_adendas_area', to='app_rrhh.area'),
        ),
        migrations.AddField(
            model_name='contratosadendas',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratosadendas',
            name='modificado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que modificó el registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datoslaborales',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados_laborales', to='app_rrhh.area'),
        ),
        migrations.AddField(
            model_name='descuentomasivo',
            name='configuracion_concepto',
            field=models.ForeignKey(limit_choices_to={'tipo': 'descuento'}, on_delete=django.db.models.deletion.PROTECT, related_name='descuentos_masivos', to='app_rrhh.configuracionremuneracion'),
        ),
        migrations.AddField(
            model_name='descuentomasivo',
            name='usuario_carga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descuentos_masivos_cargados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='datos_laborales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_planilla', to='app_rrhh.datoslaborales'),
        ),
        migrations.AddField(
            model_name='conceptoplanilla',
            name='detalle_planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='app_rrhh.detalleplanilla'),
        ),
        migrations.AddField(
            model_name='boletapago',
            name='detalle_planilla',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleta', to='app_rrhh.detalleplanilla'),
        ),
        migrations.AddField(
            model_name='documentosdigitales',
            name='digitalizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_digitalizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentosdigitales',
            name='documento_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='app_rrhh.documentosdigitales'),
        ),
        migrations.AddField(
            model_name='documentosdigitales',
            name='familiar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='app_rrhh.datosfamiliares'),
        ),
        migrations.AddField(
            model_name='documentosdigitales',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentosdigitales',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datosacademicos',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dato_academico', to='app_rrhh.documentosdigitales'),
        ),
        migrations.AddField(
            model_name='cursoscertificaciones',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curso_certificacion', to='app_rrhh.documentosdigitales'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['numero_documento'], name='empleado_numero__b2a613_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['nombres_empleado'], name='empleado_nombres_d62500_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['estado_empleado'], name='empleado_estado__3a11be_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['fecha_nacimiento'], name='empleado_fecha_n_8b3772_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['correo_personal'], name='empleado_correo__8f1298_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['genero_empleado'], name='empleado_genero__07814d_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['tipo_documento'], name='empleado_tipo_do_02c9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['sistema_pensiones'], name='empleado_sistema_1c86fc_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['tipo_comision'], name='empleado_tipo_co_b05d03_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['estado_civil'], name='empleado_estado__828326_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['tipo_sangre'], name='empleado_tipo_sa_e47bc9_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['es_padre_familia'], name='empleado_es_padr_88453e_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['es_militar'], name='empleado_es_mili_ca9eb4_idx'),
        ),
        migrations.AddField(
            model_name='documentosdigitales',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_digitales', to='app_rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_planilla', to='app_rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='datoslaborales',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_laborales', to='app_rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='datoslaborales',
            name='jefe_directo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados_laborales', to='app_rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='datosfamiliares',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='app_rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='datosacademicos',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formacion_academica', to='app_rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='cursoscertificaciones',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_certificaciones', to='app_rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='contratosadendas',
            name='empleado',
            field=models.ForeignKey(help_text='Empleado asociado al contrato/adenda', on_delete=django.db.models.deletion.CASCADE, related_name='contratos_adendas', to='app_rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='configuracionvacaciones',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_vacaciones', to='app_rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='gocevacaciones',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goces_vacaciones', to='app_rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='gocevacaciones',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goces_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialsolicitudvacaciones',
            name='usuario_accion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_vacaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialubicaciones',
            name='area_destino',
            field=models.ForeignKey(help_text='ID del área de destino', on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_destino', to='app_rrhh.area'),
        ),
        migrations.AddField(
            model_name='historialubicaciones',
            name='area_origen',
            field=models.ForeignKey(blank=True, help_text='ID del área de origen', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_origen', to='app_rrhh.area'),
        ),
        migrations.AddField(
            model_name='historialubicaciones',
            name='documento',
            field=models.ForeignKey(blank=True, help_text='ID del documento adjunto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones_documento', to='app_rrhh.documentosdigitales'),
        ),
        migrations.AddField(
            model_name='historialubicaciones',
            name='empleado',
            field=models.ForeignKey(help_text='ID del empleado', on_delete=django.db.models.deletion.CASCADE, related_name='historial_ubicaciones', to='app_rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='historialubicaciones',
            name='registrado_por_usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingempleado',
            name='empleado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='app_rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='onboardingempleado',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingempleado',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboardings_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periodovacacional',
            name='configuracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos', to='app_rrhh.configuracionvacaciones'),
        ),
        migrations.AddField(
            model_name='periodovacacional',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periodos_vacacionales', to='app_rrhh.contratosadendas'),
        ),
        migrations.AddField(
            model_name='periodovacacional',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_vacacionales_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periodovacacional',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_vacacionales', to='app_rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='gocevacaciones',
            name='periodo_vacacional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goces', to='app_rrhh.periodovacacional'),
        ),
        migrations.AddField(
            model_name='planillamensual',
            name='usuario_aprobacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planillas_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planillamensual',
            name='usuario_generacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planillas_generadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_rrhh.planillamensual'),
        ),
        migrations.AddField(
            model_name='calendariopago',
            name='planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios_pago', to='app_rrhh.planillamensual'),
        ),
        migrations.AddField(
            model_name='plantilladocumento',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_vacaciones', to='app_rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='jefe_aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas_como_jefe', to='app_rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='periodo_vacacional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='app_rrhh.periodovacacional'),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='rechazado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_rechazadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='rrhh_aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas_rrhh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialsolicitudvacaciones',
            name='solicitud_vacaciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='app_rrhh.solicitudvacaciones'),
        ),
        migrations.AddField(
            model_name='gocevacaciones',
            name='solicitud_vacaciones',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goce', to='app_rrhh.solicitudvacaciones'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['siglas_area'], name='area_siglas__255e90_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['estado_area'], name='area_estado__6d5f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['nombre_organo'], name='area_nombre__c13500_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['area_padre'], name='area_area_pa_1d5a63_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['nivel_jerarquico'], name='area_nivel_j_96d829_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['codigo_presupuestal'], name='area_codigo__b31045_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['total_empleados'], name='area_total_e_4f9815_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionuit',
            index=models.Index(fields=['anio'], name='configuraci_anio_b21674_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionuit',
            index=models.Index(fields=['estado'], name='configuraci_estado_036f7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='configuracionuit',
            constraint=models.UniqueConstraint(fields=('anio',), name='uniq_configuracion_uit_anio'),
        ),
        migrations.AddIndex(
            model_name='descuentomasivo',
            index=models.Index(fields=['periodo'], name='descuento_m_periodo_3f0496_idx'),
        ),
        migrations.AddIndex(
            model_name='descuentomasivo',
            index=models.Index(fields=['estado'], name='descuento_m_estado_529e99_idx'),
        ),
        migrations.AddIndex(
            model_name='descuentomasivo',
            index=models.Index(fields=['-fecha_carga'], name='descuento_m_fecha_c_fd69ea_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptoplanilla',
            index=models.Index(fields=['detalle_planilla'], name='concepto_pl_detalle_1ac869_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptoplanilla',
            index=models.Index(fields=['tipo'], name='concepto_pl_tipo_045406_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptoplanilla',
            index=models.Index(fields=['codigo'], name='concepto_pl_codigo_c3c02f_idx'),
        ),
        migrations.AddIndex(
            model_name='boletapago',
            index=models.Index(fields=['detalle_planilla'], name='boleta_pago_detalle_79aeea_idx'),
        ),
        migrations.AddIndex(
            model_name='boletapago',
            index=models.Index(fields=['estado'], name='boleta_pago_estado_86c3ac_idx'),
        ),
        migrations.AddIndex(
            model_name='boletapago',
            index=models.Index(fields=['-fecha_generacion'], name='boleta_pago_fecha_g_c43e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['empleado'], name='documentos__emplead_08c690_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['tipo_documento'], name='documentos__tipo_do_ec317e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['categoria'], name='documentos__categor_6d2a70_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['estado_documento'], name='documentos__estado__45a8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['fecha_vencimiento'], name='documentos__fecha_v_9cee1a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['nivel_acceso'], name='documentos__nivel_a_0d67eb_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['es_version_actual'], name='documentos__es_vers_dbe362_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['fecha_subida'], name='documentos__fecha_s_8a8d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['formato_archivo'], name='documentos__formato_517b26_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['es_documento_oficial'], name='documentos__es_docu_a542c0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['validado_por'], name='documentos__validad_ec3013_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosdigitales',
            index=models.Index(fields=['digitalizado_por'], name='documentos__digital_280aeb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentosdigitales',
            unique_together={('empleado', 'tipo_documento', 'numero_documento', 'version')},
        ),
        migrations.AddIndex(
            model_name='datoslaborales',
            index=models.Index(fields=['empleado'], name='datos_labor_emplead_330753_idx'),
        ),
        migrations.AddIndex(
            model_name='datoslaborales',
            index=models.Index(fields=['area'], name='datos_labor_area_id_3bca69_idx'),
        ),
        migrations.AddIndex(
            model_name='datoslaborales',
            index=models.Index(fields=['cargo_empleado'], name='datos_labor_cargo_e_7291e7_idx'),
        ),
        migrations.AddIndex(
            model_name='datoslaborales',
            index=models.Index(fields=['tipo_contrato'], name='datos_labor_tipo_co_343446_idx'),
        ),
        migrations.AddIndex(
            model_name='datoslaborales',
            index=models.Index(fields=['regimen_laboral'], name='datos_labor_regimen_78f6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='datoslaborales',
            index=models.Index(fields=['categoria'], name='datos_labor_categor_874bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='datoslaborales',
            index=models.Index(fields=['fecha_ingreso'], name='datos_labor_fecha_i_0a24f0_idx'),
        ),
        migrations.AddIndex(
            model_name='datoslaborales',
            index=models.Index(fields=['fecha_inicio_contrato'], name='datos_labor_fecha_i_442f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='datoslaborales',
            index=models.Index(fields=['fecha_fin_contrato'], name='datos_labor_fecha_f_2cae45_idx'),
        ),
        migrations.AddIndex(
            model_name='datoslaborales',
            index=models.Index(fields=['estado_datos'], name='datos_labor_estado__0c2b88_idx'),
        ),
        migrations.AddIndex(
            model_name='datoslaborales',
            index=models.Index(fields=['jefe_directo'], name='datos_labor_jefe_di_9012c4_idx'),
        ),
        migrations.AddIndex(
            model_name='datoslaborales',
            index=models.Index(fields=['modalidad_trabajo'], name='datos_labor_modalid_7752a9_idx'),
        ),
        migrations.AddIndex(
            model_name='datoslaborales',
            index=models.Index(fields=['jornada_laboral'], name='datos_labor_jornada_3fa2ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datoslaborales',
            unique_together={('empleado', 'fecha_inicio_contrato')},
        ),
        migrations.AddIndex(
            model_name='datosfamiliares',
            index=models.Index(fields=['empleado'], name='datos_famil_emplead_e50b70_idx'),
        ),
        migrations.AddIndex(
            model_name='datosfamiliares',
            index=models.Index(fields=['parentesco'], name='datos_famil_parente_1679ae_idx'),
        ),
        migrations.AddIndex(
            model_name='datosfamiliares',
            index=models.Index(fields=['numero_documento'], name='datos_famil_numero__f21df8_idx'),
        ),
        migrations.AddIndex(
            model_name='datosfamiliares',
            index=models.Index(fields=['fecha_nacimiento'], name='datos_famil_fecha_n_d03952_idx'),
        ),
        migrations.AddIndex(
            model_name='datosfamiliares',
            index=models.Index(fields=['es_dependiente'], name='datos_famil_es_depe_0969d9_idx'),
        ),
        migrations.AddIndex(
            model_name='datosfamiliares',
            index=models.Index(fields=['es_beneficiario'], name='datos_famil_es_bene_cb7b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='datosfamiliares',
            index=models.Index(fields=['es_contacto_emergencia'], name='datos_famil_es_cont_bb8bc3_idx'),
        ),
        migrations.AddIndex(
            model_name='datosfamiliares',
            index=models.Index(fields=['estado_familiar'], name='datos_famil_estado__faf5cb_idx'),
        ),
        migrations.AddIndex(
            model_name='datosfamiliares',
            index=models.Index(fields=['genero_familiar'], name='datos_famil_genero__8e574e_idx'),
        ),
        migrations.AddIndex(
            model_name='datosfamiliares',
            index=models.Index(fields=['tipo_documento'], name='datos_famil_tipo_do_d273c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datosfamiliares',
            unique_together={('empleado', 'numero_documento')},
        ),
        migrations.AddIndex(
            model_name='datosacademicos',
            index=models.Index(fields=['empleado'], name='datos_acade_emplead_3cc713_idx'),
        ),
        migrations.AddIndex(
            model_name='datosacademicos',
            index=models.Index(fields=['nivel_educativo'], name='datos_acade_nivel_e_c05244_idx'),
        ),
        migrations.AddIndex(
            model_name='datosacademicos',
            index=models.Index(fields=['nombre_institucion'], name='datos_acade_nombre__32e40b_idx'),
        ),
        migrations.AddIndex(
            model_name='datosacademicos',
            index=models.Index(fields=['nombre_carrera'], name='datos_acade_nombre__ff37a6_idx'),
        ),
        migrations.AddIndex(
            model_name='datosacademicos',
            index=models.Index(fields=['estado_estudios'], name='datos_acade_estado__577903_idx'),
        ),
        migrations.AddIndex(
            model_name='datosacademicos',
            index=models.Index(fields=['fecha_graduacion'], name='datos_acade_fecha_g_123ced_idx'),
        ),
        migrations.AddIndex(
            model_name='datosacademicos',
            index=models.Index(fields=['area_conocimiento'], name='datos_acade_area_co_dda48e_idx'),
        ),
        migrations.AddIndex(
            model_name='datosacademicos',
            index=models.Index(fields=['tipo_institucion'], name='datos_acade_tipo_in_4de605_idx'),
        ),
        migrations.AddIndex(
            model_name='datosacademicos',
            index=models.Index(fields=['modalidad_estudio'], name='datos_acade_modalid_d21c17_idx'),
        ),
        migrations.AddIndex(
            model_name='datosacademicos',
            index=models.Index(fields=['verificado_sunedu'], name='datos_acade_verific_bbf21d_idx'),
        ),
        migrations.AddIndex(
            model_name='datosacademicos',
            index=models.Index(fields=['estado_registro'], name='datos_acade_estado__79c0ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datosacademicos',
            unique_together={('empleado', 'nivel_educativo', 'nombre_carrera', 'nombre_institucion')},
        ),
        migrations.AlterUniqueTogether(
            name='cursoscertificaciones',
            unique_together={('empleado', 'nombre_curso', 'institucion', 'fecha_inicio')},
        ),
        migrations.AddIndex(
            model_name='contratosadendas',
            index=models.Index(fields=['empleado'], name='contratos_a_emplead_74b57c_idx'),
        ),
        migrations.AddIndex(
            model_name='contratosadendas',
            index=models.Index(fields=['area'], name='contratos_a_area_id_54979d_idx'),
        ),
        migrations.AddIndex(
            model_name='contratosadendas',
            index=models.Index(fields=['numero_contrato'], name='contratos_a_numero__cf9e10_idx'),
        ),
        migrations.AddIndex(
            model_name='contratosadendas',
            index=models.Index(fields=['fecha_fin'], name='contratos_a_fecha_f_d8eda3_idx'),
        ),
        migrations.AddIndex(
            model_name='contratosadendas',
            index=models.Index(fields=['estado'], name='contratos_a_estado_cc42d1_idx'),
        ),
        migrations.AddIndex(
            model_name='contratosadendas',
            index=models.Index(fields=['tipo_documento'], name='contratos_a_tipo_do_81d492_idx'),
        ),
        migrations.AddIndex(
            model_name='contratosadendas',
            index=models.Index(fields=['fecha_inicio'], name='contratos_a_fecha_i_401979_idx'),
        ),
        migrations.AddIndex(
            model_name='contratosadendas',
            index=models.Index(fields=['creado_por'], name='contratos_a_creado__699081_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contratosadendas',
            unique_together={('numero_contrato', 'numero_adenda')},
        ),
        migrations.AddIndex(
            model_name='configuracionvacaciones',
            index=models.Index(fields=['tipo_configuracion'], name='configuraci_tipo_co_b533b1_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionvacaciones',
            index=models.Index(fields=['area'], name='configuraci_area_id_dbfa20_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionvacaciones',
            index=models.Index(fields=['empleado'], name='configuraci_emplead_a45a01_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionvacaciones',
            index=models.Index(fields=['activo'], name='configuraci_activo_26e1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionvacaciones',
            index=models.Index(fields=['fecha_inicio_vigencia'], name='configuraci_fecha_i_899776_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionvacaciones',
            index=models.Index(fields=['fecha_fin_vigencia'], name='configuraci_fecha_f_f8d860_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracionvacaciones',
            unique_together={('tipo_configuracion', 'area', 'empleado', 'fecha_inicio_vigencia')},
        ),
        migrations.AddIndex(
            model_name='historialubicaciones',
            index=models.Index(fields=['empleado'], name='idx_empleado_id'),
        ),
        migrations.AddIndex(
            model_name='historialubicaciones',
            index=models.Index(fields=['area_origen'], name='idx_area_origen'),
        ),
        migrations.AddIndex(
            model_name='historialubicaciones',
            index=models.Index(fields=['area_destino'], name='idx_area_destino'),
        ),
        migrations.AddIndex(
            model_name='historialubicaciones',
            index=models.Index(fields=['fecha_inicio'], name='idx_fecha_inicio'),
        ),
        migrations.AddIndex(
            model_name='historialubicaciones',
            index=models.Index(fields=['tipo_movimiento'], name='idx_tipo_movimiento'),
        ),
        migrations.AddIndex(
            model_name='historialubicaciones',
            index=models.Index(fields=['estado_ubicacion'], name='historial_u_estado__ac80f1_idx'),
        ),
        migrations.AddIndex(
            model_name='historialubicaciones',
            index=models.Index(fields=['registrado_por_usuario'], name='historial_u_registr_b3b9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingempleado',
            index=models.Index(fields=['estado_onboarding'], name='onboarding__estado__d9cfa9_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingempleado',
            index=models.Index(fields=['empleado'], name='onboarding__emplead_f3f95c_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingempleado',
            index=models.Index(fields=['usuario'], name='onboarding__usuario_3e937e_idx'),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['empleado'], name='periodos_va_emplead_fffe72_idx'),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['contrato'], name='periodos_va_contrat_a5804a_idx'),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['ano_periodo'], name='periodos_va_ano_per_235d09_idx'),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['estado_periodo'], name='periodos_va_estado__f214bd_idx'),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['fecha_vencimiento'], name='periodos_va_fecha_v_c7d330_idx'),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['fecha_inicio_periodo'], name='periodos_va_fecha_i_09f735_idx'),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['fecha_fin_periodo'], name='periodos_va_fecha_f_ba3687_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='periodovacacional',
            unique_together={('empleado', 'ano_periodo', 'contrato')},
        ),
        migrations.AddIndex(
            model_name='planillamensual',
            index=models.Index(fields=['periodo'], name='planilla_me_periodo_a636eb_idx'),
        ),
        migrations.AddIndex(
            model_name='planillamensual',
            index=models.Index(fields=['modalidad'], name='planilla_me_modalid_8ab38a_idx'),
        ),
        migrations.AddIndex(
            model_name='planillamensual',
            index=models.Index(fields=['estado'], name='planilla_me_estado_90af76_idx'),
        ),
        migrations.AddIndex(
            model_name='planillamensual',
            index=models.Index(fields=['meta_presupuestal'], name='planilla_me_meta_pr_7719eb_idx'),
        ),
        migrations.AddIndex(
            model_name='planillamensual',
            index=models.Index(fields=['-fecha_creacion'], name='planilla_me_fecha_c_a4e5e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='planillamensual',
            constraint=models.UniqueConstraint(fields=('periodo', 'modalidad', 'meta_presupuestal'), name='uniq_planilla_periodo_modalidad_meta'),
        ),
        migrations.AddIndex(
            model_name='detalleplanilla',
            index=models.Index(fields=['planilla'], name='detalle_pla_planill_a74c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleplanilla',
            index=models.Index(fields=['empleado'], name='detalle_pla_emplead_ceabbe_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleplanilla',
            index=models.Index(fields=['dni'], name='detalle_pla_dni_98b301_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleplanilla',
            index=models.Index(fields=['sistema_pensiones'], name='detalle_pla_sistema_89a8b1_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleplanilla',
            index=models.Index(fields=['banco'], name='detalle_pla_banco_9fcabd_idx'),
        ),
        migrations.AddConstraint(
            model_name='detalleplanilla',
            constraint=models.UniqueConstraint(fields=('planilla', 'empleado'), name='uniq_detalle_planilla_empleado'),
        ),
        migrations.AddIndex(
            model_name='calendariopago',
            index=models.Index(fields=['planilla'], name='calendario__planill_b97353_idx'),
        ),
        migrations.AddIndex(
            model_name='calendariopago',
            index=models.Index(fields=['fecha_pago_programada'], name='calendario__fecha_p_f885ec_idx'),
        ),
        migrations.AddIndex(
            model_name='calendariopago',
            index=models.Index(fields=['estado'], name='calendario__estado_77e9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='calendariopago',
            index=models.Index(fields=['-fecha_creacion'], name='calendario__fecha_c_9cde4c_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['empleado'], name='solicitudes_emplead_5de986_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['periodo_vacacional'], name='solicitudes_periodo_f089a7_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['estado_solicitud'], name='solicitudes_estado__f20e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['fecha_inicio'], name='solicitudes_fecha_i_4c06b0_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['fecha_fin'], name='solicitudes_fecha_f_39da73_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['fecha_envio'], name='solicitudes_fecha_e_439f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['tipo_solicitud'], name='solicitudes_tipo_so_18daf3_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['aprobado_por_jefe'], name='solicitudes_aprobad_702946_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['aprobado_por_rrhh'], name='solicitudes_aprobad_0a6eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='historialsolicitudvacaciones',
            index=models.Index(fields=['solicitud_vacaciones'], name='historial_s_solicit_e869e6_idx'),
        ),
        migrations.AddIndex(
            model_name='historialsolicitudvacaciones',
            index=models.Index(fields=['tipo_accion'], name='historial_s_tipo_ac_0f74b8_idx'),
        ),
        migrations.AddIndex(
            model_name='historialsolicitudvacaciones',
            index=models.Index(fields=['usuario_accion'], name='historial_s_usuario_a91dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='historialsolicitudvacaciones',
            index=models.Index(fields=['fecha_accion'], name='historial_s_fecha_a_b4c445_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['empleado'], name='goces_vacac_emplead_2c13ce_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['periodo_vacacional'], name='goces_vacac_periodo_27100d_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['estado_goce'], name='goces_vacac_estado__bfafb7_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['fecha_inicio_real'], name='goces_vacac_fecha_i_4c084c_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['fecha_fin_real'], name='goces_vacac_fecha_f_db8eab_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['fecha_reincorporacion'], name='goces_vacac_fecha_r_19d35a_idx'),
        ),
        migrations.AddIndex(
            model_name='gocevacaciones',
            index=models.Index(fields=['reincorporado'], name='goces_vacac_reincor_f3ee2f_idx'),
        ),
    ]
