# Generated by Django 5.2.13 on 2026-04-26 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_rrhh', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingempleado',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingempleado',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboardings_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='onboardingempleado',
            index=models.Index(fields=['estado_onboarding'], name='onboarding__estado__d9cfa9_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingempleado',
            index=models.Index(fields=['empleado'], name='onboarding__emplead_f3f95c_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingempleado',
            index=models.Index(fields=['usuario'], name='onboarding__usuario_3e937e_idx'),
        ),
    ]
