# Generated by Django 4.2.28 on 2026-02-19 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0003_modulos_menu_jerarquico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='modulo',
            field=models.ForeignKey(db_column='modulo_id', on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='app_rrhh.modulos'),
        ),
        migrations.CreateModel(
            name='OnboardingEmpleado',
            fields=[
                ('onboarding_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_onboarding', models.CharField(choices=[('pendiente_datos', 'Pendiente de Datos Personales'), ('pendiente_documentos', 'Pendiente de Documentos'), ('pendiente_validacion', 'Pendiente de Validacion RRHH'), ('observado', 'Observado - Requiere Correccion'), ('completado', 'Completado')], default='pendiente_datos', max_length=25)),
                ('datos_personales_completos', models.BooleanField(default=False)),
                ('datos_laborales_completos', models.BooleanField(default=False)),
                ('dni_subido', models.BooleanField(default=False)),
                ('declaraciones_juradas_subidas', models.BooleanField(default=False)),
                ('certificados_academicos_subidos', models.BooleanField(default=False)),
                ('certificados_trabajo_subidos', models.BooleanField(default=False)),
                ('documentos_familiares_subidos', models.BooleanField(default=False)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('email_bienvenida_enviado', models.BooleanField(default=False)),
                ('fecha_email_bienvenida', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='app_rrhh.empleado')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboardings_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboarding_empleado',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['estado_onboarding'], name='onboarding__estado__d9cfa9_idx'), models.Index(fields=['empleado'], name='onboarding__emplead_f3f95c_idx'), models.Index(fields=['usuario'], name='onboarding__usuario_3e937e_idx')],
            },
        ),
    ]
