# Generated by Codex on 2026-02-23

from django.db import migrations, models
import django.db.models.deletion


def backfill_periodo_contrato(apps, schema_editor):
    PeriodoVacacional = apps.get_model('app_rrhh', 'PeriodoVacacional')
    ContratosAdendas = apps.get_model('app_rrhh', 'ContratosAdendas')

    for periodo in PeriodoVacacional.objects.filter(contrato__isnull=True):
        contrato = (
            ContratosAdendas.objects.filter(
                empleado_id=periodo.empleado_id,
                tipo_documento__startswith='CONTRATO',
                fecha_inicio__lte=periodo.fecha_inicio_periodo,
            )
            .filter(models.Q(fecha_fin__isnull=True) | models.Q(fecha_fin__gte=periodo.fecha_inicio_periodo))
            .order_by('-fecha_inicio', '-contrato_id')
            .first()
        )
        if contrato:
            periodo.contrato_id = contrato.contrato_id
            periodo.save(update_fields=['contrato'])


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0005_alter_documentosdigitales_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodovacacional',
            name='contrato',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='periodos_vacacionales',
                to='app_rrhh.contratosadendas',
            ),
        ),
        migrations.RunPython(backfill_periodo_contrato, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='periodovacacional',
            unique_together={('empleado', 'ano_periodo', 'contrato')},
        ),
    ]
