# Generated by Django 4.2.28 on 2026-03-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0007_vacaciones_mediodia_decimal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='permiso',
            new_name='permiso_modulo_380ffc_idx',
            old_name='permiso_modulo__e0d3af_idx',
        ),
        migrations.AlterField(
            model_name='permiso',
            name='modulo',
            field=models.CharField(db_column='modulo', help_text='ID del módulo según MODULES_CONFIG (ej: empleados, vacaciones, etc)', max_length=50),
        ),
        migrations.AddIndex(
            model_name='periodovacacional',
            index=models.Index(fields=['contrato'], name='periodos_va_contrat_a5804a_idx'),
        ),
    ]
