# Generated by Django 4.2.28 on 2026-03-09 03:12

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0018_remuneraciones_submenus_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaMensual',
            fields=[
                ('planilla_id', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(help_text='Formato YYYY-MM', max_length=7)),
                ('modalidad', models.CharField(choices=[('plazo_indeterminado', 'Plazo Indeterminado'), ('plazo_determinado', 'Plazo Determinado'), ('subsidio', 'Subsidio'), ('locacion', 'Locación de Servicios'), ('consultoria', 'Consultoría')], max_length=30)),
                ('meta_presupuestal', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('procesando', 'En Proceso'), ('generada', 'Generada'), ('aprobada', 'Aprobada'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('total_trabajadores', models.PositiveIntegerField(default=0)),
                ('total_remuneracion_bruta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_neto_pagar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_essalud', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_aporte_afp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_onp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('fecha_generacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_aprobacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planillas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_generacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planillas_generadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'planilla_mensual',
                'ordering': ['-periodo', 'modalidad'],
            },
        ),
        migrations.CreateModel(
            name='DetallePlanilla',
            fields=[
                ('detalle_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('sistema_pensiones', models.CharField(max_length=30)),
                ('tipo_comision_afp', models.CharField(blank=True, max_length=10, null=True)),
                ('cuspp', models.CharField(blank=True, max_length=30, null=True)),
                ('dias_laborados', models.PositiveIntegerField(default=30)),
                ('dias_no_laborados', models.PositiveIntegerField(default=0)),
                ('dias_subsidiados', models.PositiveIntegerField(default=0)),
                ('remuneracion_basica', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('asignacion_familiar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('bonificacion_especial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('otras_bonificaciones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_haberes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('aporte_afp_obligatorio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('comision_afp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('prima_seguro_afp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_afp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('aporte_onp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('renta_quinta_categoria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('descuentos_judiciales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('prestamos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('otros_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('essalud', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('datos_laborales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_planilla', to='app_rrhh.datoslaborales')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_planilla', to='app_rrhh.empleado')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_rrhh.planillamensual')),
            ],
            options={
                'db_table': 'detalle_planilla',
                'ordering': ['area_nombre', 'empleado__apellido_paterno'],
            },
        ),
        migrations.CreateModel(
            name='DescuentoMasivo',
            fields=[
                ('descuento_masivo_id', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(help_text='Formato YYYY-MM', max_length=7)),
                ('archivo_origen', models.FileField(help_text='Archivo Excel con descuentos masivos', upload_to='descuentos_masivos/%Y/%m/')),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('registros_procesados', models.PositiveIntegerField(default=0)),
                ('registros_error', models.PositiveIntegerField(default=0)),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('aplicado', 'Aplicado'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('errores_log', models.TextField(blank=True, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('configuracion_concepto', models.ForeignKey(limit_choices_to={'tipo': 'descuento'}, on_delete=django.db.models.deletion.PROTECT, related_name='descuentos_masivos', to='app_rrhh.configuracionremuneracion')),
                ('usuario_carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descuentos_masivos_cargados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'descuento_masivo',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoPlanilla',
            fields=[
                ('concepto_planilla_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('descuento', 'Descuento')], max_length=20)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('configuracion_concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_planilla', to='app_rrhh.configuracionremuneracion')),
                ('detalle_planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='app_rrhh.detalleplanilla')),
            ],
            options={
                'db_table': 'concepto_planilla',
                'ordering': ['tipo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='CalendarioPago',
            fields=[
                ('calendario_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(choices=[('mensual', 'Mensual'), ('quincenal', 'Quincenal'), ('semanal', 'Semanal'), ('extraordinario', 'Extraordinario')], max_length=20)),
                ('fecha_pago_programada', models.DateField()),
                ('fecha_pago_ejecutada', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios_pago', to='app_rrhh.planillamensual')),
                ('usuario_programacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendarios_programados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendario_pago',
                'ordering': ['fecha_pago_programada'],
            },
        ),
        migrations.CreateModel(
            name='BoletaPago',
            fields=[
                ('boleta_id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo_pdf', models.FileField(blank=True, help_text='Archivo PDF de la boleta', null=True, upload_to='boletas_pago/%Y/%m/')),
                ('estado', models.CharField(choices=[('generada', 'Generada'), ('enviada', 'Enviada'), ('descargada', 'Descargada')], default='generada', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio_email', models.DateTimeField(blank=True, null=True)),
                ('fecha_descarga', models.DateTimeField(blank=True, null=True)),
                ('hash_documento', models.CharField(blank=True, help_text='SHA-256 del PDF', max_length=64, null=True)),
                ('detalle_planilla', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleta', to='app_rrhh.detalleplanilla')),
            ],
            options={
                'db_table': 'boleta_pago',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.AddIndex(
            model_name='planillamensual',
            index=models.Index(fields=['periodo'], name='planilla_me_periodo_a636eb_idx'),
        ),
        migrations.AddIndex(
            model_name='planillamensual',
            index=models.Index(fields=['modalidad'], name='planilla_me_modalid_8ab38a_idx'),
        ),
        migrations.AddIndex(
            model_name='planillamensual',
            index=models.Index(fields=['estado'], name='planilla_me_estado_90af76_idx'),
        ),
        migrations.AddIndex(
            model_name='planillamensual',
            index=models.Index(fields=['meta_presupuestal'], name='planilla_me_meta_pr_7719eb_idx'),
        ),
        migrations.AddIndex(
            model_name='planillamensual',
            index=models.Index(fields=['-fecha_creacion'], name='planilla_me_fecha_c_a4e5e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='planillamensual',
            constraint=models.UniqueConstraint(fields=('periodo', 'modalidad', 'meta_presupuestal'), name='uniq_planilla_periodo_modalidad_meta'),
        ),
        migrations.AddIndex(
            model_name='detalleplanilla',
            index=models.Index(fields=['planilla'], name='detalle_pla_planill_a74c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleplanilla',
            index=models.Index(fields=['empleado'], name='detalle_pla_emplead_ceabbe_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleplanilla',
            index=models.Index(fields=['dni'], name='detalle_pla_dni_98b301_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleplanilla',
            index=models.Index(fields=['sistema_pensiones'], name='detalle_pla_sistema_89a8b1_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleplanilla',
            index=models.Index(fields=['banco'], name='detalle_pla_banco_9fcabd_idx'),
        ),
        migrations.AddConstraint(
            model_name='detalleplanilla',
            constraint=models.UniqueConstraint(fields=('planilla', 'empleado'), name='uniq_detalle_planilla_empleado'),
        ),
        migrations.AddIndex(
            model_name='descuentomasivo',
            index=models.Index(fields=['periodo'], name='descuento_m_periodo_3f0496_idx'),
        ),
        migrations.AddIndex(
            model_name='descuentomasivo',
            index=models.Index(fields=['estado'], name='descuento_m_estado_529e99_idx'),
        ),
        migrations.AddIndex(
            model_name='descuentomasivo',
            index=models.Index(fields=['-fecha_carga'], name='descuento_m_fecha_c_fd69ea_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptoplanilla',
            index=models.Index(fields=['detalle_planilla'], name='concepto_pl_detalle_1ac869_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptoplanilla',
            index=models.Index(fields=['tipo'], name='concepto_pl_tipo_045406_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptoplanilla',
            index=models.Index(fields=['codigo'], name='concepto_pl_codigo_c3c02f_idx'),
        ),
        migrations.AddIndex(
            model_name='calendariopago',
            index=models.Index(fields=['planilla'], name='calendario__planill_b97353_idx'),
        ),
        migrations.AddIndex(
            model_name='calendariopago',
            index=models.Index(fields=['fecha_pago_programada'], name='calendario__fecha_p_f885ec_idx'),
        ),
        migrations.AddIndex(
            model_name='calendariopago',
            index=models.Index(fields=['estado'], name='calendario__estado_77e9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='calendariopago',
            index=models.Index(fields=['-fecha_creacion'], name='calendario__fecha_c_9cde4c_idx'),
        ),
        migrations.AddIndex(
            model_name='boletapago',
            index=models.Index(fields=['detalle_planilla'], name='boleta_pago_detalle_79aeea_idx'),
        ),
        migrations.AddIndex(
            model_name='boletapago',
            index=models.Index(fields=['estado'], name='boleta_pago_estado_86c3ac_idx'),
        ),
        migrations.AddIndex(
            model_name='boletapago',
            index=models.Index(fields=['-fecha_generacion'], name='boleta_pago_fecha_g_c43e8f_idx'),
        ),
    ]
