# Generated by Django 4.2.28 on 2026-03-09 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0020_configuracion_uit_suspension_renta'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='configuracionuit',
            new_name='configuraci_anio_b21674_idx',
            old_name='app_rrhh_co_anio_idx',
        ),
        migrations.RenameIndex(
            model_name='configuracionuit',
            new_name='configuraci_estado_036f7f_idx',
            old_name='app_rrhh_co_estado_idx',
        ),
    ]
