# Generated by Django 4.2.28 on 2026-03-12 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0021_rename_app_rrhh_co_anio_idx_configuraci_anio_b21674_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosdigitales',
            name='archivo',
            field=models.FileField(upload_to='documentos_empleados/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'rar'])]),
        ),
        migrations.AlterField(
            model_name='documentosdigitales',
            name='categoria',
            field=models.CharField(choices=[('personal', 'Personal'), ('academico', 'Académico'), ('laboral', 'Laboral'), ('medico', 'Médico'), ('legal', 'Legal'), ('administrativo', 'Administrativo'), ('capacitacion', 'Capacitación'), ('evaluacion', 'Evaluación'), ('remuneraciones', 'Remuneraciones'), ('ubicacion', 'Ubicacion'), ('otros', 'Otros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosdigitales',
            name='tipo_documento',
            field=models.CharField(choices=[('dni', 'DNI'), ('pasaporte', 'Pasaporte'), ('carnet_extranjeria', 'Carnet de Extranjería'), ('licencia_conducir', 'Licencia de Conducir'), ('certificado_nacimiento', 'Certificado de Nacimiento'), ('certificado_estudios', 'Certificado de Estudios'), ('titulo_profesional', 'Título Profesional'), ('diploma', 'Diploma'), ('certificado_trabajo', 'Certificado de Trabajo'), ('carta_recomendacion', 'Carta de Recomendación'), ('cv', 'Curriculum Vitae'), ('foto', 'Fotografía'), ('certificado_medico', 'Certificado Médico'), ('certificado_antecedentes', 'Certificado de Antecedentes'), ('declaracion_jurada', 'Declaración Jurada'), ('contrato_trabajo', 'Contrato de Trabajo'), ('adenda_contrato', 'Adenda de Contrato'), ('memorandum', 'Memorándum'), ('carta_amonestacion', 'Carta de Amonestación'), ('solicitud_vacaciones', 'Solicitud de Vacaciones'), ('certificado_capacitacion', 'Certificado de Capacitación'), ('evaluacion_desempeno', 'Evaluación de Desempeño'), ('boleta_pago', 'Boleta de Pago'), ('constancia_trabajo', 'Constancia de Trabajo'), ('constancia_participacion', 'Constancia de Participación'), ('constancia_haberes', 'Constancia de Haberes'), ('resolucion_encargatura', 'Resolución de Encargatura'), ('resolucion_licencia', 'Resolución de Licencia'), ('resolucion_sancion', 'Resolución de Sanción'), ('carta_cese', 'Carta de Cese'), ('otros', 'Otros')], max_length=30),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='departamento_domicilio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='direccion_domicilio',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='distrito_domicilio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='entidad_bancaria',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viudo', 'Viudo'), ('conviviente', 'Conviviente')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='genero_empleado',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('no_especifica', 'No especifica')], default='masculino', max_length=15),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_cci',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_cuenta_bancaria',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='provincia_domicilio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono_celular',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo_comision',
            field=models.CharField(blank=True, choices=[('FLUJO', 'FLUJO'), ('MIXTA', 'MIXTA')], max_length=10, null=True),
        ),
    ]
