# Generated by Django 4.2.28 on 2026-03-12 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0022_empleado_onboarding_nullable_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaDocumento',
            fields=[
                ('plantilla_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('certificado_trabajo', 'Certificado de Trabajo'), ('constancia_laboral', 'Constancia Laboral'), ('contrato', 'Contrato'), ('adenda', 'Adenda')], help_text='Tipo de documento que genera esta plantilla', max_length=30)),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la plantilla', max_length=200)),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripcion de la plantilla')),
                ('archivo', models.FileField(help_text='Archivo .docx de la plantilla', upload_to='plantillas_word/%Y/')),
                ('activa', models.BooleanField(default=True, help_text='Si esta plantilla esta disponible para uso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Documento',
                'verbose_name_plural': 'Plantillas de Documentos',
                'db_table': 'app_rrhh_plantilla_documento',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
