# Generated by Django 4.2.28 on 2026-03-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0025_datosacademicos_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoslaborales',
            name='tipo_contrato',
            field=models.CharField(choices=[('CAS', 'CAS - Contrato Administrativo de Servicios'), ('CAP', 'CAP - Cuadro de Asignación de Personal'), ('indefinido', 'Indefinido'), ('temporal', 'Temporal'), ('practicas', 'Prácticas'), ('consultoria', 'Consultoría'), ('locacion', 'Locación de Servicios')], max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sistema_pensiones',
            field=models.CharField(choices=[('ONP', 'ONP'), ('AFP PRIMA', 'AFP PRIMA'), ('AFP INTEGRA', 'AFP INTEGRA'), ('AFP PROFUTURO', 'AFP PROFUTURO'), ('AFP HABITAT', 'AFP HABITAT'), ('PENSIONISTA-SPP', 'PENSIONISTA-SPP'), ('PENSIONISTA-CMP', 'PENSIONISTA-CMP'), ('PENSIONISTA-OTRO', 'PENSIONISTA-OTRO'), ('SIN PENSION', 'Sin Pensión')], default='ONP', max_length=20),
        ),
    ]
