# Generated by Django 5.2.13 on 2026-05-10 03:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0004_supportsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, help_text='Dotted action name, e.g. "employee.terminated".', max_length=128)),
                ('target_model', models.CharField(help_text='Dotted model label, e.g. "employees.Employee".', max_length=128)),
                ('target_id', models.CharField(db_index=True, help_text="String form of target's primary key (UUID or int as str).", max_length=64)),
                ('payload_json', models.JSONField(blank=True, default=dict, help_text='Snapshot of the mutation: before/after, reason, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, help_text='User who performed the action. Null for system-initiated events.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Audit event',
                'verbose_name_plural': 'Audit events',
                'db_table': 'audit_lite_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'action', '-created_at'], name='audit_lite__tenant__2bbb77_idx'), models.Index(fields=['target_model', 'target_id'], name='audit_lite__target__5dc622_idx')],
            },
        ),
    ]
