# Generated by Django 5.2.13 on 2026-05-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_lite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='schema_version',
            field=models.IntegerField(default=1, help_text='Payload schema version for forward-compat (ADR-D.3).'),
        ),
    ]
