# Generated by Codex on 2026-02-23

from django.db import migrations, models
import django.core.validators
import decimal


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0006_periodo_vacacional_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='medio_dia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='periodovacacional',
            name='dias_adicionales',
            field=models.DecimalField(decimal_places=1, default=decimal.Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.0')), django.core.validators.MaxValueValidator(decimal.Decimal('30.0'))]),
        ),
        migrations.AlterField(
            model_name='periodovacacional',
            name='dias_correspondientes',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.0')), django.core.validators.MaxValueValidator(decimal.Decimal('365.0'))]),
        ),
        migrations.AlterField(
            model_name='periodovacacional',
            name='dias_gozados',
            field=models.DecimalField(decimal_places=1, default=decimal.Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='periodovacacional',
            name='dias_pendientes',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='periodovacacional',
            name='dias_totales',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.0')), django.core.validators.MaxValueValidator(decimal.Decimal('365.0'))]),
        ),
        migrations.AlterField(
            model_name='periodovacacional',
            name='dias_vencidos',
            field=models.DecimalField(decimal_places=1, default=decimal.Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='dias_solicitados',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.5')), django.core.validators.MaxValueValidator(decimal.Decimal('365.0'))]),
        ),
        migrations.AlterField(
            model_name='gocevacaciones',
            name='dias_gozados',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.5')), django.core.validators.MaxValueValidator(decimal.Decimal('365.0'))]),
        ),
        migrations.AlterField(
            model_name='gocevacaciones',
            name='dias_no_gozados',
            field=models.DecimalField(decimal_places=1, default=decimal.Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.0'))]),
        ),
    ]
