# Generated by Django 4.2.28 on 2026-03-09 00:59

import app_rrhh.models.documentos_digitales
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0010_rbac_scalability_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosdigitales',
            name='archivo',
            field=models.FileField(upload_to=app_rrhh.models.documentos_digitales.documento_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'rar'])]),
        ),
        migrations.AlterField(
            model_name='documentosdigitales',
            name='categoria',
            field=models.CharField(choices=[('personal', 'Personal'), ('academico', 'Académico'), ('laboral', 'Laboral'), ('medico', 'Médico'), ('legal', 'Legal'), ('administrativo', 'Administrativo'), ('capacitacion', 'Capacitación'), ('evaluacion', 'Evaluación'), ('remuneraciones', 'Remuneraciones'), ('ubicacion', 'Ubicacion'), ('familiar', 'Familiar'), ('otros', 'Otros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosdigitales',
            name='tipo_documento',
            field=models.CharField(choices=[('dni', 'DNI'), ('pasaporte', 'Pasaporte'), ('carnet_extranjeria', 'Carnet de Extranjería'), ('licencia_conducir', 'Licencia de Conducir'), ('certificado_nacimiento', 'Certificado de Nacimiento'), ('certificado_estudios', 'Certificado de Estudios'), ('titulo_profesional', 'Título Profesional'), ('diploma', 'Diploma'), ('certificado_trabajo', 'Certificado de Trabajo'), ('carta_recomendacion', 'Carta de Recomendación'), ('cv', 'Curriculum Vitae'), ('foto', 'Fotografía'), ('certificado_medico', 'Certificado Médico'), ('certificado_antecedentes', 'Certificado de Antecedentes'), ('declaracion_jurada', 'Declaración Jurada'), ('contrato_trabajo', 'Contrato de Trabajo'), ('adenda_contrato', 'Adenda de Contrato'), ('memorandum', 'Memorándum'), ('carta_amonestacion', 'Carta de Amonestación'), ('solicitud_vacaciones', 'Solicitud de Vacaciones'), ('certificado_capacitacion', 'Certificado de Capacitación'), ('evaluacion_desempeno', 'Evaluación de Desempeño'), ('boleta_pago', 'Boleta de Pago'), ('constancia_trabajo', 'Constancia de Trabajo'), ('constancia_participacion', 'Constancia de Participación'), ('constancia_haberes', 'Constancia de Haberes'), ('resolucion_encargatura', 'Resolución de Encargatura'), ('resolucion_licencia', 'Resolución de Licencia'), ('resolucion_sancion', 'Resolución de Sanción'), ('carta_cese', 'Carta de Cese'), ('acta_matrimonio', 'Acta de Matrimonio'), ('certificado_union_hecho', 'Certificado de Unión de Hecho'), ('dni_familiar', 'DNI de Familiar'), ('otros', 'Otros')], max_length=30),
        ),
    ]
