# Generated by Django 5.2.4 on 2026-03-08 00:00

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_rrhh", "0011_fix_upload_to_and_add_doc_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionRemuneracion",
            fields=[
                (
                    "configuracion_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("afp", "AFP"),
                            ("ingreso", "Ingreso"),
                            ("descuento", "Descuento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("codigo", models.CharField(max_length=30)),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=6
                    ),
                ),
                (
                    "monto_fijo",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("aplica_base_imponible", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=1)),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        default="activo",
                        max_length=10,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "configuracion_remuneracion",
                "ordering": ["tipo", "orden", "nombre"],
            },
        ),
        migrations.AddIndex(
            model_name="configuracionremuneracion",
            index=models.Index(fields=["tipo"], name="configuracio_tipo_48d376_idx"),
        ),
        migrations.AddIndex(
            model_name="configuracionremuneracion",
            index=models.Index(
                fields=["codigo"], name="configuracio_codigo_7f6853_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="configuracionremuneracion",
            index=models.Index(
                fields=["estado"], name="configuracio_estado_11ce03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="configuracionremuneracion",
            index=models.Index(fields=["orden"], name="configuracio_orden_93dd65_idx"),
        ),
        migrations.AddConstraint(
            model_name="configuracionremuneracion",
            constraint=models.UniqueConstraint(
                fields=("tipo", "codigo"),
                name="uniq_config_remuneracion_tipo_codigo",
            ),
        ),
    ]
