# Generated by Django 5.2.4 on 2026-03-08 00:30

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_rrhh", "0012_configuracion_remuneracion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionAfp",
            fields=[
                ("afp_config_id", models.AutoField(primary_key=True, serialize=False)),
                ("afp_nombre", models.CharField(max_length=80)),
                (
                    "vigencia_mes",
                    models.CharField(help_text="Formato YYYY-MM", max_length=7),
                ),
                (
                    "aporte_obligatorio_pct",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("10.000"), max_digits=6
                    ),
                ),
                (
                    "comision_flujo_pct",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=6
                    ),
                ),
                (
                    "comision_mixta_pct",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=6
                    ),
                ),
                (
                    "prima_seguro_pct",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1.370"), max_digits=6
                    ),
                ),
                (
                    "remuneracion_max_asegurable",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        default="activo",
                        max_length=10,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "configuracion_afp",
                "ordering": ["-vigencia_mes", "afp_nombre"],
            },
        ),
        migrations.AddIndex(
            model_name="configuracionafp",
            index=models.Index(
                fields=["afp_nombre"], name="configuracio_afp_nom_d467af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="configuracionafp",
            index=models.Index(
                fields=["vigencia_mes"], name="configuracio_vigenci_76f4ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="configuracionafp",
            index=models.Index(
                fields=["estado"], name="configuracio_estado_235a43_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="configuracionafp",
            constraint=models.UniqueConstraint(
                fields=("afp_nombre", "vigencia_mes"),
                name="uniq_config_afp_nombre_vigencia",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionremuneracion",
            name="tipo",
            field=models.CharField(
                choices=[("ingreso", "Ingreso"), ("descuento", "Descuento")],
                max_length=20,
            ),
        ),
    ]
