# Generated by Django 4.2.28 on 2026-03-09 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0013_configuracion_afp_and_adjust_remuneracion_choices'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='configuracionafp',
            new_name='configuraci_afp_nom_8564da_idx',
            old_name='configuracio_afp_nom_d467af_idx',
        ),
        migrations.RenameIndex(
            model_name='configuracionafp',
            new_name='configuraci_vigenci_12071c_idx',
            old_name='configuracio_vigenci_76f4ea_idx',
        ),
        migrations.RenameIndex(
            model_name='configuracionafp',
            new_name='configuraci_estado_34bdb1_idx',
            old_name='configuracio_estado_235a43_idx',
        ),
        migrations.RenameIndex(
            model_name='configuracionremuneracion',
            new_name='configuraci_tipo_48de49_idx',
            old_name='configuracio_tipo_48d376_idx',
        ),
        migrations.RenameIndex(
            model_name='configuracionremuneracion',
            new_name='configuraci_codigo_2938f0_idx',
            old_name='configuracio_codigo_7f6853_idx',
        ),
        migrations.RenameIndex(
            model_name='configuracionremuneracion',
            new_name='configuraci_estado_d391c8_idx',
            old_name='configuracio_estado_11ce03_idx',
        ),
        migrations.RenameIndex(
            model_name='configuracionremuneracion',
            new_name='configuraci_orden_eb4d3b_idx',
            old_name='configuracio_orden_93dd65_idx',
        ),
    ]
