# Generated by Django 4.2.28 on 2026-03-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0023_add_plantilla_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Institución Pública', help_text='Nombre de la institución', max_length=300)),
                ('ruc', models.CharField(default='20000000000', help_text='RUC de la institución', max_length=20)),
                ('direccion', models.CharField(default='', help_text='Dirección de la institución', max_length=300)),
                ('distrito', models.CharField(blank=True, default='', max_length=100)),
                ('provincia', models.CharField(blank=True, default='Lima', max_length=100)),
                ('departamento', models.CharField(blank=True, default='Lima', max_length=100)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=150)),
                ('web', models.URLField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, help_text='Logo institucional', null=True, upload_to='empresa/')),
                ('representante_legal', models.CharField(blank=True, default='', help_text='Nombre del representante legal', max_length=200)),
                ('cargo_representante', models.CharField(blank=True, default='', help_text='Cargo del representante', max_length=200)),
                ('dni_representante', models.CharField(blank=True, default='', help_text='DNI del representante', max_length=20)),
                ('resolucion_creacion', models.CharField(blank=True, default='', help_text='Resolución de creación', max_length=200)),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'db_table': 'configuracion_empresa',
            },
        ),
        migrations.AlterField(
            model_name='contratosadendas',
            name='tipo_documento',
            field=models.CharField(choices=[('CAS_INDETERMINADO', 'CAS a Plazo Indeterminado'), ('CAS_DETERMINADO', 'CAS a Plazo Determinado'), ('CAS_SUPLENCIA', 'CAS a Plazo Determinado Suplencia'), ('LEY_728_FIJO', 'Ley 728 a Plazo Fijo'), ('LEY_728_FIJO_SUPLENCIA', 'Ley 728 a Plazo Fijo Suplencia'), ('LEY_728_INDETERMINADO', 'Ley 728 a Plazo Indeterminado'), ('LEY_276_INDETERMINADO', 'Ley 276 a Plazo Indeterminado'), ('ADENDA_SALARIAL', 'Adenda Salarial'), ('ADENDA_CARGO', 'Adenda de Cambio de Cargo'), ('ADENDA_HORARIO', 'Adenda de Cambio de Horario'), ('ADENDA_EXTENSION', 'Adenda de Extension')], help_text='Tipo de documento contractual', max_length=25),
        ),
    ]
