# Generated by Django 4.2.28 on 2026-03-15 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rrhh', '0024_configuracionempresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosacademicos',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dato_academico', to='app_rrhh.documentosdigitales'),
        ),
        migrations.AddField(
            model_name='documentosdigitales',
            name='familiar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='app_rrhh.datosfamiliares'),
        ),
        migrations.CreateModel(
            name='CursosCertificaciones',
            fields=[
                ('curso_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=200)),
                ('institucion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('horas', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado_registro', models.CharField(default='activo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curso_certificacion', to='app_rrhh.documentosdigitales')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_certificaciones', to='app_rrhh.empleado')),
            ],
            options={
                'db_table': 'cursos_certificaciones',
                'unique_together': {('empleado', 'nombre_curso', 'institucion', 'fecha_inicio')},
            },
        ),
    ]
