# Generated by Django 5.2.13 on 2026-05-09 06:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=11)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise'), ('govtech', 'GovTech')], max_length=20)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('max_users', models.IntegerField(default=10)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenancy_tenant',
                'indexes': [models.Index(fields=['slug'], name='tenancy_ten_slug_46265a_idx'), models.Index(fields=['status', 'plan'], name='tenancy_ten_status_00074a_idx')],
            },
        ),
    ]
