# Generated by Django 5.2.13 on 2026-05-09 06:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_tenantinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('actions_count', models.IntegerField(default=0)),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_sessions_initiated', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_sessions_received', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_sessions', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Support Session',
                'verbose_name_plural': 'Support Sessions',
                'db_table': 'tenancy_supportsession',
                'indexes': [models.Index(fields=['tenant', 'started_at'], name='tenancy_sup_tenant__f7cd4f_idx'), models.Index(fields=['staff_user', 'started_at'], name='tenancy_sup_staff_u_6f7923_idx')],
            },
        ),
    ]
