# Generated by Django 5.2.13 on 2026-05-09 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('tenancy', '0004_supportsession'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academicrecord',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='certification',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='certification',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='numero_documento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='academicrecord',
            unique_together={('tenant', 'empleado', 'nivel_educativo', 'nombre_carrera', 'nombre_institucion')},
        ),
        migrations.AlterUniqueTogether(
            name='certification',
            unique_together={('tenant', 'empleado', 'nombre_curso', 'institucion', 'fecha_inicio')},
        ),
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together={('tenant', 'empleado', 'numero_documento')},
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('tenant', 'numero_documento'), name='unique_employee_doc_per_tenant'),
        ),
    ]
