# Generated by Django 5.2.13 on 2026-05-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_academicrecord_unique_together_and_more'),
        ('tenancy', '0004_supportsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='correo_personal',
            field=models.EmailField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('correo_personal__isnull', False), models.Q(('correo_personal', ''), _negated=True)), fields=('tenant', 'correo_personal'), name='employees_employee_unique_tenant_correo'),
        ),
    ]
