# Generated by Django 5.2.13 on 2026-05-11 01:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_correo_personal_and_more'),
        ('tenancy', '0004_supportsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('dni', 'DNI'), ('ce', 'Carné de Extranjería'), ('passport', 'Pasaporte'), ('ptp', 'PTP')], default='dni', max_length=10)),
                ('document_number', models.CharField(db_index=True, max_length=20)),
                ('first_names', models.CharField(max_length=100)),
                ('last_names', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'No binario / sin declarar')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('highest_education', models.CharField(blank=True, max_length=100)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='candidates/%Y/%m/')),
                ('source', models.CharField(blank=True, help_text='Acquisition channel: internal_referral | website | linkedin | servir | walk_in | other.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'candidate',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'document_number'], name='candidate_tenant__4d95e5_idx'), models.Index(fields=['tenant', 'email'], name='candidate_tenant__60eff0_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'document_type', 'document_number'), name='unique_candidate_doc_per_tenant')],
            },
        ),
    ]
