# Generated by Django 5.2.13 on 2026-05-11 01:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_b9_candidate'),
        ('organization', '0010_b8_position_register'),
        ('tenancy', '0004_supportsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, help_text='Display code, e.g. REQ-2026-0001. Auto-generation deferred.', max_length=30)),
                ('justification', models.CharField(choices=[('new_position', 'Plaza nueva'), ('replacement', 'Reemplazo por baja'), ('expansion', 'Crecimiento del área'), ('temporary', 'Cobertura temporal')], max_length=20)),
                ('justification_notes', models.TextField(blank=True)),
                ('requested_count', models.PositiveIntegerField(default=1)),
                ('requested_start_date', models.DateField(blank=True, null=True)),
                ('estimated_monthly_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending_approval', 'Pendiente de aprobación'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada'), ('fulfilled', 'Cubierta')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_finance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approved_by_hr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='organization.department')),
                ('plaza', models.ForeignKey(blank=True, help_text='Optional concrete plaza being filled. Null = new plaza.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='organization.plaza')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='organization.position')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions_requested', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'personnel_requisition',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='personnel_r_tenant__7999cb_idx'), models.Index(fields=['position'], name='personnel_r_positio_df5049_idx'), models.Index(fields=['department'], name='personnel_r_departm_d19676_idx')],
            },
        ),
    ]
