# Generated by Django 5.2.13 on 2026-05-11 01:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_b9_personnel_requisition'),
        ('organization', '0010_b8_position_register'),
        ('tenancy', '0004_supportsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('sector_mode', models.CharField(choices=[('private', 'Sector privado'), ('public_servir', 'Sector público — concurso SERVIR (Ley 30057)')], db_index=True, default='private', max_length=20)),
                ('posting_kind', models.CharField(choices=[('internal', 'Interna'), ('external', 'Externa'), ('mixed', 'Mixta')], default='external', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada'), ('in_evaluation', 'En evaluación'), ('closed', 'Cerrada'), ('cancelled', 'Cancelada'), ('declared_void', 'Declarada desierta')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('applications_open_at', models.DateField(blank=True, null=True)),
                ('applications_close_at', models.DateField(blank=True, null=True)),
                ('results_announce_at', models.DateField(blank=True, null=True)),
                ('bases_url', models.URLField(blank=True, help_text='URL pública a las bases del concurso.')),
                ('bases_file', models.FileField(blank=True, null=True, upload_to='postings/bases/%Y/%m/')),
                ('transparency_published', models.BooleanField(default=False, help_text='SERVIR Art. 5: publicación obligatoria en portal institucional + SERVIR.')),
                ('closed_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpe_entry', models.ForeignKey(blank=True, help_text='Plaza del CPE (Ley 30057, B.8) que esta convocatoria cubre.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postings', to='organization.positionregisterentry')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='employees.personnelrequisition')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'job_posting',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'sector_mode', 'status'], name='job_posting_tenant__406677_idx'), models.Index(fields=['requisition'], name='job_posting_requisi_909ac5_idx')],
            },
        ),
    ]
