# Generated by Django 5.2.13 on 2026-05-11 01:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_b9_job_posting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('curricular', 'Evaluación curricular'), ('knowledge', 'Prueba de conocimientos'), ('psycho', 'Evaluación psicolaboral'), ('interview', 'Entrevista personal'), ('technical', 'Prueba técnica'), ('reference', 'Verificación de referencias'), ('other', 'Otra')], max_length=20)),
                ('name', models.CharField(help_text='Custom display name (e.g. "Examen técnico SQL"); defaults to kind label.', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_eliminatoria', models.BooleanField(default=True, help_text='Si es eliminatoria, fallar score < min_score quita al candidato.')),
                ('min_score', models.DecimalField(decimal_places=2, default=0, help_text='Puntaje mínimo aprobatorio (e.g. 14.00 para SERVIR conocimientos).', max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='Peso en cuadro de méritos final (0-100). Sumatoria de pesos = 100 en posting.', max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='employees.jobposting')),
            ],
            options={
                'db_table': 'selection_stage',
                'ordering': ['posting', 'order'],
                'constraints': [models.UniqueConstraint(fields=('posting', 'order'), name='unique_stage_order_per_posting')],
            },
        ),
    ]
