# Generated by Django 5.2.13 on 2026-05-11 01:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_b9_selection_stage'),
        ('tenancy', '0004_supportsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('received', 'Recibida'), ('reviewing', 'En revisión'), ('in_evaluation', 'En evaluación'), ('eliminated', 'Eliminada'), ('finalist', 'Finalista'), ('offered', 'Oferta enviada'), ('accepted', 'Aceptada'), ('hired', 'Contratada'), ('rejected', 'Rechazada'), ('withdrawn', 'Retirada por candidato')], db_index=True, default='received', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('elimination_reason', models.TextField(blank=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('custom_cv_file', models.FileField(blank=True, help_text='Posting-specific CV; falls back to candidate.cv_file when null.', null=True, upload_to='applications/cv/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='employees.candidate')),
                ('eliminated_at_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.selectionstage')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='employees.jobposting')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'job_application',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['posting', 'status'], name='job_applica_posting_02ea2d_idx'), models.Index(fields=['candidate'], name='job_applica_candida_463b80_idx')],
                'constraints': [models.UniqueConstraint(fields=('posting', 'candidate'), name='unique_application_per_posting_candidate')],
            },
        ),
    ]
