# Generated by Django 5.2.13 on 2026-05-11 01:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_b9_candidate_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeritRanking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField(help_text='1 = ganador; 2..N = lista de espera; ≥N+1 con outcome="eliminated".')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('outcome', models.CharField(choices=[('winner', 'Ganador'), ('waiting_list', 'Lista de espera'), ('eliminated', 'Eliminado')], max_length=20)),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('score_breakdown', models.JSONField(blank=True, default=dict, help_text='Per-stage detail: {stage_id: {name, score, weight, weighted}}')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='employees.jobapplication')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='employees.jobposting')),
            ],
            options={
                'db_table': 'merit_ranking',
                'ordering': ['posting', 'rank'],
                'indexes': [models.Index(fields=['posting', 'outcome'], name='merit_ranki_posting_d42079_idx')],
                'constraints': [models.UniqueConstraint(fields=('posting', 'application'), name='unique_ranking_per_posting_application')],
            },
        ),
    ]
