# Generated by Django 5.2.13 on 2026-05-15 03:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_b12_dossier'),
        ('employees', '0010_b9_merit_ranking'),
        ('organization', '0010_b8_position_register'),
        ('tenancy', '0004_supportsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_label', models.CharField(help_text='Snapshot of position name for historical accuracy', max_length=200)),
                ('department_label', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('motive', models.CharField(blank=True, help_text='hiring | promotion | rotation | encargatura | designation | end', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_history', to='employees.employee')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.position')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'job_history',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['tenant', 'employee', 'start_date'], name='job_history_tenant__c32f17_idx')],
            },
        ),
        migrations.CreateModel(
            name='SwornDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('no_parentesco', 'No parentesco (Ley de nepotismo)'), ('no_incompatibilidad', 'No incompatibilidad / doble percepción'), ('intereses', 'Declaración de intereses'), ('impedimentos', 'Impedimentos para contratar')], max_length=30)),
                ('declared_at', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.digitaldocument')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sworn_declarations', to='employees.employee')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'sworn_declaration',
                'ordering': ['-declared_at'],
                'indexes': [models.Index(fields=['tenant', 'employee', 'kind'], name='sworn_decla_tenant__f87394_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer', models.CharField(max_length=200)),
                ('position_title', models.CharField(max_length=200)),
                ('sector', models.CharField(choices=[('privado', 'Privado'), ('publico', 'Público'), ('ong', 'ONG / Tercer sector'), ('autonomo', 'Trabajo autónomo / freelance')], default='privado', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('responsibilities', models.TextField(blank=True)),
                ('reference_name', models.CharField(blank=True, max_length=200)),
                ('reference_phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='employees.employee')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'work_experience',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['tenant', 'employee'], name='work_experi_tenant__fb1627_idx')],
            },
        ),
    ]
