# Generated by Django 5.2.13 on 2026-05-17 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0011_b12_legajo_content'),
        ('identity', '0003_user_is_vyntia_staff'),
        ('organization', '0011_b13_displacement'),
        ('tenancy', '0004_supportsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('rit', 'Reglamento Interno de Trabajo'), ('codigo_etica', 'Código de Ética'), ('reglamento_sst', 'Reglamento Interno de SST'), ('politica_datos', 'Política de Datos Personales'), ('manual_funciones', 'Manual de Organización y Funciones'), ('procedimiento', 'Procedimiento'), ('otro', 'Otro')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('approved', 'Aprobado'), ('published', 'Publicado'), ('retired', 'Retirado')], db_index=True, default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_owned', to='organization.department')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies_owned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'policy',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('content_html', models.TextField(blank=True, help_text='Cuerpo HTML de la versión (renderizable a PDF)')),
                ('pdf_file', models.FileField(blank=True, help_text='PDF rendereado o subido manualmente (max ~10 MB)', null=True, upload_to='policies/%Y/%m/')),
                ('change_summary', models.TextField(blank=True, help_text='Qué cambia respecto a la versión anterior')),
                ('effective_date', models.DateField(blank=True, help_text='Fecha en que entra en vigencia (puede ser futura)', null=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('under_review', 'En revisión'), ('approved', 'Aprobada'), ('published', 'Publicada'), ('retired', 'Retirada')], db_index=True, default='draft', max_length=15)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='policies.policy')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'policy_version',
                'ordering': ['policy', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='PolicyPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('published_at', models.DateTimeField()),
                ('target_audience', models.CharField(choices=[('all', 'Todos los empleados'), ('role', 'Por rol'), ('area', 'Por área'), ('employee', 'Empleados específicos')], default='all', max_length=15)),
                ('requires_acknowledgment', models.BooleanField(default=True)),
                ('acknowledgment_deadline', models.DateField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.department')),
                ('target_employees', models.ManyToManyField(blank=True, related_name='+', to='employees.employee')),
                ('target_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.role')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('policy_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publication', to='policies.policyversion')),
            ],
            options={
                'db_table': 'policy_publication',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyApprovalFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En curso'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], db_index=True, default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('policy_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_flow', to='policies.policyversion')),
            ],
            options={
                'db_table': 'policy_approval_flow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='current_version',
            field=models.ForeignKey(blank=True, help_text='Última versión publicada (apunta al PolicyVersion vigente)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='policies.policyversion'),
        ),
        migrations.CreateModel(
            name='PolicyApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('role_hint', models.CharField(blank=True, help_text='Etiqueta opcional del rol esperado (RRHH, Legal, Gerencia, etc.)', max_length=64)),
                ('decision', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], db_index=True, default='pending', max_length=15)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_approval_steps', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='policies.policyapprovalflow')),
            ],
            options={
                'db_table': 'policy_approval_step',
                'ordering': ['flow', 'order'],
                'constraints': [models.UniqueConstraint(fields=('flow', 'order'), name='unique_step_order_per_flow')],
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('acknowledged', 'Acusada'), ('expired', 'Vencida'), ('declined', 'Rechazada por empleado')], db_index=True, default='pending', max_length=15)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('signature_kind', models.CharField(blank=True, choices=[('canvas', 'Firma manuscrita digital'), ('typed', 'Firma escrita'), ('checkbox', 'Aceptación con checkbox'), ('none', 'Sin firma')], max_length=15)),
                ('signature_payload', models.TextField(blank=True, help_text='Canvas base64 / texto firma / "true" para checkbox. Max ~200KB.')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('declined_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgments', to='employees.employee')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='policies.policypublication')),
            ],
            options={
                'db_table': 'policy_acknowledgment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'employee', 'status'], name='policy_ackn_tenant__e87328_idx'), models.Index(fields=['publication', 'status'], name='policy_ackn_publica_a43927_idx')],
                'constraints': [models.UniqueConstraint(fields=('publication', 'employee'), name='unique_acknowledgment_per_publication_employee')],
            },
        ),
        migrations.AddIndex(
            model_name='policyversion',
            index=models.Index(fields=['tenant', 'policy'], name='policy_vers_tenant__3830fd_idx'),
        ),
        migrations.AddIndex(
            model_name='policyversion',
            index=models.Index(fields=['status'], name='policy_vers_status_dfc9c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.UniqueConstraint(fields=('policy', 'version_number'), name='unique_policy_version_number'),
        ),
        migrations.AddIndex(
            model_name='policypublication',
            index=models.Index(fields=['tenant', '-published_at'], name='policy_publ_tenant__c5ba42_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['tenant', 'kind'], name='policy_tenant__c292f2_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['tenant', 'status'], name='policy_tenant__0ec57a_idx'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(fields=('tenant', 'kind', 'title'), name='unique_policy_title_per_kind'),
        ),
    ]
