# Generated by Django 5.2.13 on 2026-05-17 22:13

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_b12_legajo_content'),
        ('organization', '0011_b13_displacement'),
        ('policies', '0001_b15a_policy_models'),
        ('tenancy', '0004_supportsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('fiscal_year', models.PositiveIntegerField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('archived', 'Archivada')], db_index=True, default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_matrices_owned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'compliance_matrix',
                'ordering': ['-fiscal_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceObligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('sunat', 'SUNAT'), ('sunafil', 'SUNAFIL'), ('mintra', 'MINTRA'), ('mtpe', 'MTPE'), ('servir', 'SERVIR'), ('essalud', 'EsSalud'), ('onp', 'ONP'), ('afp', 'AFP'), ('interno', 'Interno'), ('otro', 'Otro')], default='otro', max_length=15)),
                ('frequency', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('unica', 'Única'), ('ad_hoc', 'Ad-hoc')], default='mensual', max_length=15)),
                ('severity', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('next_due_date', models.DateField()),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('cumplido', 'Cumplido'), ('vencido', 'Vencido')], db_index=True, default='pendiente', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='policies.compliancematrix')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_obligation',
                'ordering': ['next_due_date', 'severity'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('archivo', 'Archivo'), ('link', 'Enlace'), ('nota', 'Nota')], default='archivo', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='compliance/%Y/%m/')),
                ('url', models.URLField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='policies.complianceobligation')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'compliance_evidence',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='HRStrategicPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('fiscal_year', models.PositiveIntegerField(db_index=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('completed', 'Completado'), ('archived', 'Archivado')], db_index=True, default='draft', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategic_plans_owned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'hr_strategic_plan',
                'ordering': ['-fiscal_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Peso porcentual del objetivo (0-100)', max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='policies.hrstrategicplan')),
            ],
            options={
                'db_table': 'strategic_objective',
                'ordering': ['plan', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('formula_note', models.TextField(blank=True, help_text='Cómo se calcula el KPI (ej: "rotación = bajas/headcount promedio")')),
                ('unit', models.CharField(blank=True, help_text='%, N, S/., días, etc.', max_length=15)),
                ('target', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('actual', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('on_track', 'On track'), ('at_risk', 'En riesgo'), ('off_track', 'Fuera de meta'), ('done', 'Cumplido')], db_index=True, default='on_track', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='policies.strategicobjective')),
            ],
            options={
                'db_table': 'kpi',
                'ordering': ['objective', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SuccessionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('fiscal_year', models.PositiveIntegerField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('archived', 'Archivado')], db_index=True, default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='succession_plans_owned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'succession_plan',
                'ordering': ['-fiscal_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criticality', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('risk_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.position')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_positions', to='policies.successionplan')),
            ],
            options={
                'db_table': 'key_position',
                'ordering': ['plan', 'criticality', 'position_id'],
            },
        ),
        migrations.CreateModel(
            name='SuccessorCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('readiness_level', models.PositiveSmallIntegerField(choices=[(1, 'Ready now'), (2, 'Ready in 1 year'), (3, 'Ready in 2 years'), (4, 'Development needed')], default=4)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.employee')),
                ('key_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='policies.keyposition')),
            ],
            options={
                'db_table': 'successor_candidate',
                'ordering': ['key_position', 'order', 'readiness_level'],
            },
        ),
        migrations.CreateModel(
            name='WorkforcePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('fiscal_year', models.PositiveIntegerField(db_index=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('completed', 'Completado'), ('archived', 'Archivado')], db_index=True, default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workforce_plans_owned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'workforce_plan',
                'ordering': ['-fiscal_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeadcountProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_headcount', models.PositiveIntegerField(default=0)),
                ('projected_headcount', models.PositiveIntegerField(default=0)),
                ('target_quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], default='Q1', max_length=2)),
                ('justification', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, help_text='Si null, proyección global del plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.department')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.position')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='policies.workforceplan')),
            ],
            options={
                'db_table': 'headcount_projection',
                'ordering': ['plan', 'target_quarter', 'area_id', 'position_id'],
            },
        ),
        migrations.AddIndex(
            model_name='compliancematrix',
            index=models.Index(fields=['tenant', 'fiscal_year'], name='compliance__tenant__237cdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='compliancematrix',
            constraint=models.UniqueConstraint(fields=('tenant', 'fiscal_year', 'name'), name='unique_matrix_per_year_name'),
        ),
        migrations.AddIndex(
            model_name='complianceobligation',
            index=models.Index(fields=['matrix', 'status'], name='compliance__matrix__cbc502_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceobligation',
            index=models.Index(fields=['next_due_date'], name='compliance__next_du_df7041_idx'),
        ),
        migrations.AddConstraint(
            model_name='complianceobligation',
            constraint=models.UniqueConstraint(fields=('matrix', 'code'), name='unique_obligation_code_per_matrix'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['obligation', '-captured_at'], name='compliance__obligat_2fad79_idx'),
        ),
        migrations.AddIndex(
            model_name='hrstrategicplan',
            index=models.Index(fields=['tenant', 'fiscal_year'], name='hr_strategi_tenant__a2a19a_idx'),
        ),
        migrations.AddIndex(
            model_name='hrstrategicplan',
            index=models.Index(fields=['tenant', 'status'], name='hr_strategi_tenant__9a2c44_idx'),
        ),
        migrations.AddConstraint(
            model_name='hrstrategicplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'fiscal_year', 'name'), name='unique_strategic_plan_per_year_name'),
        ),
        migrations.AddConstraint(
            model_name='strategicobjective',
            constraint=models.UniqueConstraint(fields=('plan', 'code'), name='unique_objective_code_per_plan'),
        ),
        migrations.AddIndex(
            model_name='successionplan',
            index=models.Index(fields=['tenant', 'fiscal_year'], name='succession__tenant__fd7c23_idx'),
        ),
        migrations.AddConstraint(
            model_name='successionplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'fiscal_year', 'name'), name='unique_succession_plan_per_year_name'),
        ),
        migrations.AddConstraint(
            model_name='keyposition',
            constraint=models.UniqueConstraint(fields=('plan', 'position'), name='unique_key_position_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='successorcandidate',
            constraint=models.UniqueConstraint(fields=('key_position', 'employee'), name='unique_candidate_per_key_position'),
        ),
        migrations.AddIndex(
            model_name='workforceplan',
            index=models.Index(fields=['tenant', 'fiscal_year'], name='workforce_p_tenant__57bf90_idx'),
        ),
        migrations.AddIndex(
            model_name='workforceplan',
            index=models.Index(fields=['tenant', 'status'], name='workforce_p_tenant__dcb788_idx'),
        ),
        migrations.AddConstraint(
            model_name='workforceplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'fiscal_year', 'name'), name='unique_workforce_plan_per_year_name'),
        ),
        migrations.AddIndex(
            model_name='headcountprojection',
            index=models.Index(fields=['plan', 'target_quarter'], name='headcount_p_plan_id_b2bc77_idx'),
        ),
    ]
